"""BWKI 数据源配置 — 按领域组织搜索查询"""

DOMAINS = {
    "01_cognitive_science": {
        "name": "认知科学",
        "queries": [
            "Sapir-Whorf hypothesis linguistic relativity evidence",
            "language shapes thought empirical studies",
            "conceptual change theory education",
            "mental models language cognition",
            "bilingual cognitive advantage research",
            "linguistic relativity criticism debate",
            "thought without language debate",
            "color perception language effect",
            "spatial reasoning language influence",
            "grammatical gender cognition effects",
        ],
        "platforms": ["exa", "arxiv", "jina"],
        "target_count": 300,
    },
    "02_linguistics": {
        "name": "语言学",
        "queries": [
            "cross-lingual comparison methodology",
            "multilingual corpus analysis",
            "syntax thought relationship linguistics",
            "linguistic diversity cognitive implications",
            "translation equivalence problems",
            "untranslatable concepts languages",
            "word color across languages",
            "metaphor culture language",
            "pragmatics cross-cultural communication",
            "language contact cognitive effects",
        ],
        "platforms": ["exa", "arxiv", "jina", "twitter"],
        "target_count": 400,
    },
    "03_education": {
        "name": "教育学",
        "queries": [
            "bilingual education cognitive benefits",
            "cognitive load theory multimedia",
            "learning analytics student modeling",
            "personalized learning language",
            "multilingual education research 2024 2025",
            "second language acquisition cognitive",
            "metacognition bilingual students",
            "language immersion program outcomes",
            "cross-lingual transfer education",
            "student engagement multilingual classroom",
        ],
        "platforms": ["exa", "arxiv", "jina"],
        "target_count": 200,
    },
    "04_ai_education": {
        "name": "AI教育",
        "queries": [
            "LLM education tutoring multilingual",
            "NLP concept extraction student text",
            "AI feedback multilingual writing",
            "prompt engineering education",
            "GPT bilingual education study",
            "knowledge tracing NLP",
        ],
        "platforms": ["exa", "arxiv", "github"],
        "target_count": 200,
    },
    "05_graph_theory": {
        "name": "图论",
        "queries": [
            "knowledge graph construction methods",
            "conceptual graph representation",
            "graph edit distance algorithm",
            "graph similarity measures",
            "ontology engineering knowledge representation",
            "semantic network cognitive science",
        ],
        "platforms": ["exa", "arxiv", "github"],
        "target_count": 200,
    },
    "06_cross_lingual_kg": {
        "name": "跨语言知识图谱",
        "queries": [
            "cross-lingual knowledge graph alignment",
            "multilingual embeddings survey",
            "entity matching multilingual",
            "cross-lingual transfer learning NLP",
            "multilingual BERT concept extraction",
            "parallel corpus knowledge graph",
            "language-agnostic knowledge representation",
            "zero-shot cross-lingual classification",
        ],
        "platforms": ["exa", "arxiv", "github", "huggingface"],
        "target_count": 400,
    },
    "07_cultural_psychology": {
        "name": "文化心理学",
        "queries": [
            "bilingual cognition research 2024",
            "cultural framing effect decision making",
            "emotion expression across cultures",
            "moral reasoning language influence",
            "self-construal bilingual culture",
            "collectivism individualism language",
            "cultural dimensions Hofstede language",
            "bilingual identity formation",
            "language and cultural values",
            "cross-cultural communication patterns",
        ],
        "platforms": ["exa", "arxiv", "jina"],
        "target_count": 300,
    },
    "08_visualization": {
        "name": "可视化",
        "queries": [
            "knowledge graph visualization d3.js",
            "3D network graph three.js",
            "force-directed layout algorithm",
            "interactive graph exploration UI",
            "semantic web visualization tools",
            "graph visualization Python networkx",
            "node-link diagram optimization",
            "hierarchical graph layout algorithms",
        ],
        "platforms": ["exa", "arxiv", "github"],
        "target_count": 150,
    },
    "09_research_database": {
        "name": "研究数据库",
        "queries": [
            "language thought cognition survey paper",
            "cross-lingual NLP benchmark",
            "graph neural network language understanding",
            "computational linguistics trends 2024 2025",
            "multimodal language cognition",
            "LLM multilingual capabilities evaluation",
        ],
        "platforms": ["exa", "arxiv"],
        "target_count": 300,
    },
    "10_methodology": {
        "name": "方法论",
        "queries": [
            "graph edit distance computation",
            "Jaccard similarity knowledge graphs",
            "embedding evaluation metrics NLP",
            "statistical analysis bilingual experiments",
            "experiment design cognitive science",
            "precision recall F1 NLP evaluation",
            "cross-lingual evaluation benchmark",
            "ablation study methodology AI",
        ],
        "platforms": ["exa", "arxiv", "jina"],
        "target_count": 150,
    },
    "12_experts": {
        "name": "领域专家",
        "queries": [
            "Sapir-Whorf hypothesis researcher professor",
            "computational linguistics professor cross-lingual",
            "cognitive linguistics researcher bilingualism",
            "knowledge graph researcher multilingual",
            "NLP professor language cognition",
            "multilingual NLP research lab",
            "bilingual cognition neuroscience lab",
            "cross-lingual semantics research group",
        ],
        "platforms": ["exa", "arxiv"],
        "target_count": 150,
    },
}
