const TRANSLATIONS = { en: {
page_title: 'LinguaGraph — Cross-Lingual Knowledge Structure Analysis',
nav_home: 'Top', nav_validation: 'Evidence', nav_findings: 'Findings', nav_method: 'Method', nav_limits: 'Limits', nav_sources: 'Sources', nav_curriculum: 'Curriculum', nav_cogspace: '3D Graph', nav_labs: 'Mini Labs', nav_paper: 'Paper', nav_open: 'Open Science',
hero_kicker: 'BWKI 2026 · Multilingual AI Audit',
hero_title: 'How do different languages organize the <em>same knowledge?</em>',
hero_sub: 'Textbook knowledge graphs (Chinese, German, English) measured against open-weight vector baselines — with every limit printed next to every number.',
stat_rep: 'replication runs / models (file-truth 62/57/186)', stat_graph: 'nodes · relations · groups (233 rendered)',
stat_f1: 'social ≈0.94 Developing · harness ≈0.65 · blind review pending',
hero_scope: 'frozen = citable · placeholder = shape only, no significance · pending = not yet measured. Nothing on this page upgrades itself.',
cta_evidence: 'See the evidence →', cta_findings: 'Findings A–E', cta_3d: '3D Knowledge Graph',
kick_evidence: 'Evidence', validation_title: 'Validation', validation_sub: 'Trust first: what was checked, on how much data, with which limits.',
val_gold_t: 'Gold labels: 92', val_gold_d: '20 hand-annotated math (Mature C9a) + 72 machine-seeded social (Developing C9b, agent-panel-reviewed, human-review pending).',
tag_developing: 'Developing', val_bench_t: 'Extraction benchmark: 19 models', val_bench_d: 'F1 range 0.55–0.67, used only for extractor selection — never for language claims.',
val_roster_t: 'Replication roster: 59 + 26', val_roster_d: '59 full runs (54 models, all ZH-DE significant) + 26 collecting incl. qwen-max n=26/30 (parked, 2 sparse-boundary, 1 quarantined). File-truth 62/57/186.',
val_margin_t: 'Margin: 59/59, p<0.01', val_margin_d: '500 permutations; 9 of 177 EN-involving tests n.s. West 11/11 (0.155; without luna 10/10, 0.148), CN 48/48 (0.130) — underpowered as vendor comparison. Perm file-truth 62/62.',
kick_findings: 'Findings', findings_title: 'Findings A–E', findings_sub: 'Five claims, each with its limit attached. Preliminary until stated otherwise.',
fa_t: 'A · Density peaks early', fa_lead: 'Curriculum graphs densify in middle school, then thin out (CDS 0.271 → 0.073, 3.7×).',
fa_frozen: 'Frozen snapshot: computed on the June-2026 dense pipeline (574-node generation, dense code path since lost). Kept frozen, never recomputed — see forensic notes.',
fb_t: 'B · Shallow hierarchies', fb_lead: 'Concept depth ≤ 8 (math ≤ 8); 83% of concepts are hierarchy roots.', fb_frozen: 'Frozen snapshot, same provenance as A.',
fc_t: 'C · Language separates structure', fc_lead: 'Textbook LDS-K: zh-de 0.519 far below EN-involving ≈0.93 (0.933 / 0.938). The raw zh-de closeness was falsified as a label artifact (T1 decontamination 0.556 → 0.020).',
fc_tier_sum: 'Two-Tier control: what vectors (don’t) show',
fc_tier_d: 'Open-weight embeddings (nomic-embed-text-v1.5, 768 dims, 934 terms) compress all three pairs into 0.48–0.52 (spread 0.0445) and do not reproduce the textbook split (spread 0.419). Rank order only — never raw values. Vectors are the control baseline, never the evidence.',
fd_t: 'D · Systems differ in coverage', fd_lead: 'Textbook–curriculum coverage varies widely — granularity (safest reading) and governance (hypothesis) both fit.',
fe_t: 'E · Humans can’t separate it (between-subject)', fe_lead: 'N=15 falsifies ΔLDS > 0 between-subject (human LDS-C ≈ split-half floor); the LLM within-subject margin (+0.08–0.09) shows the signal exists. Earlier simulation comparison withdrawn.',
fe_probe_sum: 'Humanities falsification probe (one-way only)',
fe_probe_d: 'An independent humanities slice can weaken the “curriculum-specific” claim but never confirm the math result. Pass: math splits, humanities doesn’t → curriculum-specific. Alarm: both split → downgrade to “shared cross-domain”. Current: pilot N=8 (0.704/0.727/0.751) placeholder — no pass/alarm call.',
kick_method: 'Method', method_title: 'Methodology in five steps', method_sub: 'Extract → align → measure (LDS) → null-test (500 permutations) → replicate (59 models).',
m1_t: '1 · Extract', m1_d: '68 textbook files → 741 concepts / 665 relations, temperature=0, multi-model audit.',
m2_t: '2 · Align', m2_d: '219 trilingual groups; hard matching (lowercase, ß→ss, synonym map). Unmatched stays unmatched.',
m3_t: '3 · Measure', m3_d: 'LDS = 1 − mean(GED similarity, node/edge Jaccard). Frozen: 0.519 / 0.933 / 0.938.',
m4_t: '4 · Null-test', m4_d: '500 label permutations; p<0.004 is the resolution limit (1/500), not tuning. ZH-DE 59/59 pass, margin floor 0.033.',
m5_t: '5 · Replicate', m5_d: 'Identical P1 protocol on 59 measurements (54 models): mostly DashScope + bare-hosts/Kilo/Cohere/NIM/Cloudflare/LM-Studio/opencode-go. Availability sample, not a preregistered matrix.',
method_prov: 'Provenance: HF model SHAs are today’s HEADs, not experiment pins; served revision UNVERIFIED; local phi file is a community quant build (snapshot + App. W).',
prov_m1_btn: 'Show A/B runs', prov_m1_out: 'temperature=0, two runs: agreement 0.59–0.73, disagreement 27–41%. Single runs are snapshots.', prov_m1_sum: 'Provenance: extraction', prov_m1_why: 'Why: temperature=0 is not deterministic — one run alone carries no number.', prov_m1_chain: 'data/math_extractions/merged/merged_concepts.json → scripts/math_graph_pipeline/merge_extractions.py → data/math_extractions/merged/pipeline_snapshot.json → research/numbers_ssot_20260916.json · frozen_figures (556 nodes / 517 relations / 219 groups).',
prov_m2_sum: 'Provenance: alignment', prov_m2_why: 'Why: hard matching is a visible rule — what does not match stays unmatched.', prov_m2_chain: 'data/math_extractions/merged/aligned_data.json (total_aligned_groups 219) → scripts/math_graph_pipeline/align_languages.py → manifest.json (alignment.aligned_groups 219) → SSOT frozen_figures (219 groups).',
prov_m3_lab: 'Drag, release = frozen', prov_m3_sum: 'Provenance: measurement', prov_m3_why: 'Why: LDS is a formula, not a fit — the value is fixed.', prov_m3_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/reproduce_lds_binary.py → research/reproduce_headline_20260916.json (claim = recompute 0.519) → SSOT lds_k_tier1 (0.519 / 0.933 / 0.938).',
prov_m4_btn: 'run 50 perms', prov_m4_note: 'Null sketch (50 of 500 shown); p<0.004 is resolution 1/500, margin floor 0.033. ZH-DE 59/59.', prov_m4_sum: 'Provenance: null test', prov_m4_why: 'Why: p<0.004 is the resolution limit, not tuning — more permutations change nothing about it.', prov_m4_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/fig4_null_model.py → research/numbers_ssot_20260916.json → field macro_perm (n_perm 500, p 0.004, floor 0.033).',
prov_m5_btn: 'Toggle: ZH-DE / EN-involving', prov_m5_a: 'ZH-DE: 59/59 — all green.', prov_m5_b: 'EN-involving: 177 tests, 9 marked n.s.', prov_m5_sum: 'Provenance: replication', prov_m5_why: 'Why: 59 identical-protocol runs separate signal (ZH-DE 59/59) from noise (9/177 EN n.s.).', prov_m5_chain: 'manifest.json (pipeline_version 2.0) → scripts/run_dashscope_batch.py → research/numbers_ssot_20260916.json → field replication (59 measurements / 54 models / 177 tests, 9/177 n.s.).',
kick_limits: 'Limits', limits_title: 'Limitations', limits_sub: 'Every limit, before the conclusions. No silent upgrades.',
l1_t: 'Chunking boundaries', l1_d: 'Section-level chunks; cross-section references count as dangling. Bias is one-sided and conservative.',
l2_t: 'Hard-match penalty', l2_d: 'Synonymous-but-differently-spelled pairs are penalized by construction; sensitivity is single-digit.',
l3_t: 'Sparse annotation', l3_d: 'Human pilot N=8 is a shape placeholder; powered design is N=30. 219 aligned vs 359 unaligned groups.',
l4_t: 'temperature=0 is not deterministic', l4_d: 'Ensemble intra self-agreement only 0.59–0.73 (≈27–41% run disagreement). Single-run values are snapshots with fluctuation bands.',
l5_t: 'Snapshot instability', l5_d: 'Vote totals mix two threshold scales and must be shown split; inter means across refills are not comparable — no trend claims.',
l6_t: 'Small samples', l6_d: '92 gold labels suffice for overall F1, not for per-language per-domain splits. German math F1 (0.506) has high variance.',
kick_sources: 'Sources', sources_title: 'Sources', sources_sub: '204 textbook titles: 32 math · 83 physics · 89 chemistry. Full table in v1 archive.',
src_math_t: 'Mathematics · 32', src_math_d: 'CN / DE / UK / US textbooks, section-level JSON.',
src_phys_t: 'Physics · 83', src_phys_d: 'Exploratory stream; physics LDS as discipline control.',
src_chem_t: 'Chemistry · 89', src_chem_d: 'Exploratory stream; chemistry LDS as discipline control.',
kick_curr: 'Curriculum', curr_title: 'Curriculum analysis', curr_sub: 'Coverage: NRW 12.7% → CN 95.4%. Three competing explanations — granularity (safest) fits best.',
curr_a_t: 'A · Granularity ✕', curr_a_d: 'Finer-grained standards list more concepts — rejected as sole cause.',
curr_b_t: 'B · Governance ✓', curr_b_d: 'Centralized systems cover more — hypothesis, paper §8.6.',
curr_c_t: 'C · Division !', curr_c_d: 'Tracked vs comprehensive splits — open question.',
kick_cs: 'Explore', cs_title: 'Interactive CognitiveSpace', cs_sub: 'Mathematics subgraph: 556 nodes · 233 rendered links (of 517) · 219 groups.', cs_open: 'Open the 3D graph →', kick_labs: 'Hands on', labs_title: 'Mini Labs', labs_sub: 'No separate pages: the experiments live inside the text. Run the method, hunt a counterexample, switch a limit off.', lab1_t: 'Reproduce lab', lab1_d: 'Five steps, five controls: align a word, move the LDS threshold, run 50 permutations, light up the 59-run roster.', lab2_t: 'Counterexample hunter', lab2_d: "Eight tough cases side by side in three languages — with the ruling why they don't overturn claim C.", lab3_t: 'Limit switchboard', lab3_d: "Six limits as switches: turn one off and watch which findings go dim — plus the misreading you'd fall for.", lab_open: 'Open →',
kick_paper: 'Paper', paper_title: 'Paper', paper_sub: 'Nine core chapters (~161KB) + PDF (243KB). Appendix W is exploratory and outside the review evidence.', paper_pdf: 'Download PDF',
kick_open: 'Open Science', open_title: 'Open Science', open_sub: 'Code, data, figures — and contact.',
open_code_t: 'Code', open_code_d: '84 pytest suite; reproduction guide in submission docs; weight vectors via GitHub Release.',
open_data_t: 'Dataset', open_data_d: '68 math extractions + lds_c measurements; PII excluded from the submission package.',
open_contact_t: 'Contact', open_contact_d: 'Via school supervisor (see ethics consent). Reviews and second ratings welcome.',
footer_note: 'Full detail table in the v1 archive.',
prov_fc_sum: 'Counterexamples: 8 hardest trilingual matches (drawer)',
prov_fc_why: 'Why this drawer: these are the 8 most similar trilingual math groups in data/math_extractions/merged/merged_concepts.json — if any single shared concept could overturn claim C, it would be one of these.',
cx_1: '[concepts#45] Skalarprodukt / inner product / 内积 · refs 4 (de 2, en 1, zh 1) — aliases "Skalarprodukt, dot product, inner product, 点积". Ruling: a shared node label leaves edge structure untouched, so it cannot close the LDS-K split (spread 0.419).',
cx_2: '[concepts#52] Ableitung / derivative / 导数 · refs 4 (de 1, en 2, zh 1) — aliases "Ableitung, Derivative, Differentialquotient, Differenzialquotient, derivative, derivative function, differential coefficient, 导函数, 微商". Ruling: claim C averages 219 groups, so one aligned calculus core term cannot move the corpus mean by itself.',
cx_3: '[concepts#54] Funktion / function / 函数 · refs 5 (de 1, en 2, zh 2) — aliases "Function, Funktion, function". Ruling: this is exactly the T1 label-artifact class already decontaminated (0.556 → 0.020), so counting it again would double-count the falsified closeness.',
cx_4: '[concepts#43] Kern / kernel, null space / 核, 零空间 (线性变换的核) · refs 3 (de 1, en 1, zh 1) — aliases "Kern, kernel, null space, 核, 零空间". Ruling: hard matching already credits this synonym cluster inside the 0.519 figure, so it argues within the claim, not against it.',
cx_5: '[concepts#29] charakteristische Gleichung / characteristic equation / 特征方程 · refs 4 (de 1, en 1, zh 2) — aliases "characteristic equation, charakteristische Gleichung". Ruling: Tier-2 vectors align this trio too yet compress all pairs to 0.48–0.52 (spread 0.0445), confirming vectors cannot reproduce the textbook split either way.',
cx_6: '[concepts#12] Vektor / vector / 向量 · refs 4 (de 1, en 2, zh 1) — aliases "Vektor, vector". Ruling: a universal linear-algebra loanword predicts vocabulary overlap but no convergence of relation graphs, which is what LDS-K measures.',
cx_7: '[concepts#53] Grenzwert / limit / 极限 · refs 4 (de 1, en 2, zh 1) — aliases "Grenzwert, Limes, Limit, limit". Ruling: node-level agreement on core analysis is fully compatible with zh-de edge divergence at corpus level.',
cx_8: '[concepts#42] lineare Abbildung / linear transformation / 线性变换, 线性映射 · refs 3 (de 1, en 1, zh 1) — aliases "linear transformation, lineare Abbildung, 线性映射". Ruling: one clean triple out of 219 aligned vs 359 unaligned groups cannot overturn a corpus statistic significant in 59/59 permutation runs.',
prov_fc_chain: 'Number chain: Tier-1 textbook LDS-K 0.519 / 0.933 / 0.938 (src/scoring.py:122; research/consensus_v4_20260916.json) · T1 decontamination 0.556 → 0.020 · Tier-2 vectors 0.4804 / 0.5249 / 0.4888, spread 0.0445 vs textbook spread 0.419 · groups data/math_extractions/merged/merged_concepts.json concepts #12, #29, #42, #43, #45, #52, #53, #54 (ref counts per language quoted from each cross_references array).',
prov_fc_src: 'Source: merged file data/math_extractions/merged/merged_concepts.json · code and data <a href="https://github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph">github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph</a> — frozen numbers only, nothing recomputed here.',
limsw_link: 'switch me off',
limsw_warn1: 'Misreading if switched off: cross-section links look free, so the CDS floor (0.271 → 0.073) reads denser than it is — findings A, B, C stay preliminary, never stronger.',
limsw_warn2: 'Misreading if switched off: zh-de 0.519 reads as real convergence — it is a penalized-by-construction value with single-digit sensitivity, so claim C keeps its split.',
limsw_warn3: 'Misreading if switched off: the N=8 pilot shape (0.704/0.727/0.751) reads as evidence — it is a placeholder until N=30, so findings D and E stay shape-only.',
limsw_warn4: 'Misreading if switched off: single-run values read as constants — with ≈27–41% run disagreement they are snapshots with fluctuation bands, so A, B, C keep their bands.',
limsw_warn5: 'Misreading if switched off: mixed vote totals read as a trend — two threshold scales must stay split and inter means across refills are not comparable, so A and B show no trend.',
limsw_warn6: 'Misreading if switched off: per-split F1 reads as solid — 92 gold labels cover overall F1 only and German math F1 (0.506) is high-variance, so C and E stay at overall scope.',
curr_ev_a: 'Evidence bar: NRW floor 12.7% — fine-grained standards alone cannot explain the gap (rejected as sole cause).',
curr_ev_b: 'Evidence bar: CN ceiling 95.4% — centralized coverage hypothesis, paper §8.6.',
curr_ev_c: 'Evidence scale 12.7% → 95.4% — tracked vs comprehensive split stays an open question.'
},
de: {
page_title: 'LinguaGraph — Mehrsprachige Wissensstrukturanalyse',
nav_home: 'Top', nav_validation: 'Belege', nav_findings: 'Befunde', nav_method: 'Methode', nav_limits: 'Grenzen', nav_sources: 'Quellen', nav_curriculum: 'Curriculum', nav_cogspace: '3D-Graph', nav_labs: 'Mini-Labore', nav_paper: 'Paper', nav_open: 'Open Science',
hero_kicker: 'BWKI 2026 · Mehrsprachiges KI-Audit',
hero_title: 'Wie organisieren verschiedene Sprachen <em>dasselbe Wissen?</em>',
hero_sub: 'Lehrbuch-Wissensgraphen (Chinesisch, Deutsch, Englisch) gegen Open-Weight-Vektorbaselines — jede Grenze steht neben jeder Zahl.',
stat_rep: 'Replikationsläufe / Modelle (Datei-Wahrheit 62/57/186)', stat_graph: 'Knoten · Relationen · Gruppen (233 gerendert)',
stat_f1: 'sozial ≈0,94 Developing · Harness ≈0,65 · Blind-Review ausstehend',
hero_scope: 'frozen = zitierbar · placeholder = nur Form, keine Signifikanz · pending = noch nicht gemessen. Nichts auf dieser Seite stuft sich selbst hoch.',
cta_evidence: 'Zu den Belegen →', cta_findings: 'Befunde A–E', cta_3d: '3D-Wissensgraph',
kick_evidence: 'Belege', validation_title: 'Validierung', validation_sub: 'Erst Vertrauen: was geprüft wurde, auf wie vielen Daten, mit welchen Grenzen.',
val_gold_t: 'Gold-Labels: 92', val_gold_d: '20 hand-annotierte Mathe (Mature C9a) + 72 maschinen-geseedete Sozial (Developing C9b, Agent-Panel-reviewed, Human-Review pending).',
tag_developing: 'Developing', val_bench_t: 'Extraktions-Benchmark: 19 Modelle', val_bench_d: 'F1-Spanne 0,55–0,67, nur zur Extraktorauswahl — nie für Sprachbehauptungen.',
val_roster_t: 'Replikations-Roster: 59 + 26', val_roster_d: '59 vollständige Läufe (54 Modelle, alle ZH-DE signifikant) + 26 sammelnd inkl. qwen-max n=26/30 (geparkt, 2 spärlich-Grenze, 1 Quarantäne). Datei-Wahrheit 62/57/186.',
val_margin_t: 'Marge: 59/59, p<0,01', val_margin_d: '500 Permutationen; 9 von 177 EN-haltigen Tests n.s. West 11/11 (0,155; ohne luna 10/10, 0,148), CN 48/48 (0,130) — als Anbietervergleich unterpowert. Perm file-truth 62/62.',
kick_findings: 'Befunde', findings_title: 'Befunde A–E', findings_sub: 'Fünf Aussagen, jede mit ihrer Grenze. Preliminary bis anders vermerkt.',
fa_t: 'A · Dichte kulminiert früh', fa_lead: 'Curriculum-Graphen verdichten sich in der Mittelstufe, dann aus (CDS 0,271 → 0,073; 3,7×).',
fa_frozen: 'Eingefrorener Schnappschuss: Juni-2026-dichte Pipeline (574-Knoten-Generation, dichter Codepfad verloren). Eingefroren, nie neuberechnet — s. Forensik-Notizen.',
fb_t: 'B · Flache Hierarchien', fb_lead: 'Konzepttiefe ≤ 8 (Mathe ≤ 8); 83 % der Konzepte sind Hierarchiewurzeln.', fb_frozen: 'Eingefrorener Schnappschuss, gleiche Provenienz wie A.',
fc_t: 'C · Sprache trennt Struktur', fc_lead: 'Lehrbuch-LDS-K: zh-de 0,519 weit unter EN-haltig ≈0,93 (0,933 / 0,938). Die rohe zh-de-Nähe wurde als Label-Artefakt falsifiziert (T1-Dekontamination 0,556 → 0,020).',
fc_tier_sum: 'Two-Tier-Kontrolle: was Vektoren (nicht) zeigen',
fc_tier_d: 'Open-Weight-Embeddings (nomic-embed-text-v1.5, 768 dims, 934 Terme) komprimieren alle drei Paare auf 0,48–0,52 (Spread 0,0445) und reproduzieren den Lehrbuch-Split nicht (Spread 0,419). Nur Rangfolge — nie Rohwerte. Vektoren sind Kontroll-Baseline, nie Evidenz.',
fd_t: 'D · Systeme decken anders ab', fd_lead: 'Lehrbuch-Curriculum-Abdeckung variiert stark — Granularität (sicherste Lesart) und Governance (Hypothese) passen beide.',
fe_t: 'E · Menschen trennen es nicht (between-subject)', fe_lead: 'N=15 falsifiziert ΔLDS > 0 between-subject (human LDS-C ≈ Split-Half-Boden); die LLM-Within-Subject-Marge (+0,08–0,09) zeigt: Signal existiert. Früherer Simulationsvergleich zurückgezogen.',
fe_probe_sum: 'Humanities-Falsifikationssonde (nur einseitig)',
fe_probe_d: 'Eine unabhängige Humanities-Scheibe kann die „curriculum-spezifisch“-Behauptung schwächen, aber das Mathe-Ergebnis nie bestätigen. Pass: Mathe splittet, Humanities nicht → curriculum-spezifisch. Alarm: beide splitten → Downgrade auf „shared cross-domain“. Aktuell: Pilot N=8 (0,704/0,727/0,751) Platzhalter — kein Pass/Alarm-Call.',
kick_method: 'Methode', method_title: 'Methodik in fünf Schritten', method_sub: 'Extrahieren → Alignieren → Messen (LDS) → Null-Test (500 Permutationen) → Replizieren (59 Modelle).',
m1_t: '1 · Extrahieren', m1_d: '68 Lehrbuch-Dateien → 741 Konzepte / 665 Relationen, temperature=0, Multi-Modell-Audit.',
m2_t: '2 · Alignieren', m2_d: '219 dreisprachige Gruppen; hartes Matching (Kleinbuchstaben, ß→ss, Synonym-Map). Unverknüpft bleibt unverknüpft.',
m3_t: '3 · Messen', m3_d: 'LDS = 1 − mean(GED-Ähnlichkeit, Knoten/Kanten-Jaccard). Frozen: 0,519 / 0,933 / 0,938.',
m4_t: '4 · Null-Test', m4_d: '500 Label-Permutationen; p<0,004 ist Auflösungsgrenze (1/500), kein Tuning. ZH-DE 59/59 bestehen, Marge-Boden 0,033.',
m5_t: '5 · Replizieren', m5_d: 'Identisches P1-Protokoll auf 59 Messungen (54 Modelle): meist DashScope + Bare-Hosts/Kilo/Cohere/NIM/Cloudflare/LM-Studio/opencode-go. Verfügbarkeitsstichprobe, keine präregistrierte Matrix.',
method_prov: 'Provenienz: HF-Modell-SHAs sind heutige HEADs, keine Experiment-Pins; served revision UNVERIFIED; lokale phi-Datei ist Community-Quant-Build (Snapshot + Anh. W).',
prov_m1_btn: 'A/B-Runs zeigen', prov_m1_out: 'temperature=0, zwei Runs: Übereinstimmung 0,59–0,73, Divergenz 27–41 %. Einzelwerte sind Schnappschüsse.', prov_m1_sum: 'Provenienz: Extraktion', prov_m1_why: 'Warum: temperature=0 ist nicht deterministisch — ein Run allein trägt keine Zahl.', prov_m1_chain: 'data/math_extractions/merged/merged_concepts.json → scripts/math_graph_pipeline/merge_extractions.py → data/math_extractions/merged/pipeline_snapshot.json → research/numbers_ssot_20260916.json · frozen_figures (556 Knoten / 517 Relationen / 219 Gruppen).',
prov_m2_sum: 'Provenienz: Alignment', prov_m2_why: 'Warum: Hart-Matching ist eine sichtbare Regel — was nicht passt, bleibt unverknüpft.', prov_m2_chain: 'data/math_extractions/merged/aligned_data.json (total_aligned_groups 219) → scripts/math_graph_pipeline/align_languages.py → manifest.json (alignment.aligned_groups 219) → SSOT frozen_figures (219 Gruppen).',
prov_m3_lab: 'Ziehen, loslassen = Freeze', prov_m3_sum: 'Provenienz: Messung', prov_m3_why: 'Warum: LDS ist eine Formel, kein Fit — der Wert liegt fest.', prov_m3_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/reproduce_lds_binary.py → research/reproduce_headline_20260916.json (Claim = Recompute 0,519) → SSOT lds_k_tier1 (0,519 / 0,933 / 0,938).',
prov_m4_btn: '50 Permutationen laufen lassen', prov_m4_note: 'Null-Skizze (50 von 500 gezeigt); p<0,004 ist Auflösung 1/500, Marge-Boden 0,033. ZH-DE 59/59.', prov_m4_sum: 'Provenienz: Null-Test', prov_m4_why: 'Warum: p<0,004 ist Auflösungsgrenze, kein Tuning — mehr Permutationen ändern daran nichts.', prov_m4_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/fig4_null_model.py → research/numbers_ssot_20260916.json → Feld macro_perm (n_perm 500, p 0,004, floor 0,033).',
prov_m5_btn: 'Wechseln: ZH-DE / EN-haltig', prov_m5_a: 'ZH-DE: 59/59 — alle grün.', prov_m5_b: 'EN-haltig: 177 Tests, 9 markiert n.s.', prov_m5_sum: 'Provenienz: Replikation', prov_m5_why: 'Warum: 59 Protokoll-identische Runs trennen Signal (ZH-DE 59/59) von Rauschen (9/177 EN n.s.).', prov_m5_chain: 'manifest.json (pipeline_version 2.0) → scripts/run_dashscope_batch.py → research/numbers_ssot_20260916.json → Feld replication (59 Messungen / 54 Modelle / 177 Tests, 9/177 n.s.).',
kick_limits: 'Grenzen', limits_title: 'Limitationen', limits_sub: 'Jede Grenze vor den Schlussfolgerungen. Keine stillen Hochstufungen.',
l1_t: 'Chunking-Grenzen', l1_d: 'Abschnitts-Chunks; Querverweise zählen als dangling. Bias einseitig und konservativ.',
l2_t: 'Hart-Match-Strafe', l2_d: 'Synonyme, anders geschrieben, werden konstruktionsbedingt bestraft; Sensitivität einstellig.',
l3_t: 'Spärliche Annotation', l3_d: 'Human-Pilot N=8 ist Form-Platzhalter; powered Design ist N=30. 219 aligniert vs 359 unaligniert.',
l4_t: 'temperature=0 ist nicht deterministisch', l4_d: 'Ensemble-intra nur 0,59–0,73 (≈27–41 % Run-Divergenz). Einzelwerte sind Schnappschüsse mit Schwankungsband.',
l5_t: 'Schnappschuss-Instabilität', l5_d: 'Voten-Summen mischen zwei Schwellen-Skalen, getrennt zeigen; Inter-Mittel über Refills nicht vergleichbar — keine Trendbehauptungen.',
l6_t: 'Kleine Stichproben', l6_d: '92 Gold-Labels reichen für Gesamt-F1, nicht für Pro-Sprache-Pro-Domäne-Splits. Deutsch-Mathe-F1 (0,506) hochvariabel.',
kick_sources: 'Quellen', sources_title: 'Quellen', sources_sub: '204 Lehrbuchtitel: 32 Mathe · 83 Physik · 89 Chemie. Volltabelle im v1-Archiv.',
src_math_t: 'Mathematik · 32', src_math_d: 'CN-/DE-/UK-/US-Lehrbücher, Abschnitts-JSON.',
src_phys_t: 'Physik · 83', src_phys_d: 'Explorativer Stream; Physik-LDS als Disziplinkontrolle.',
src_chem_t: 'Chemie · 89', src_chem_d: 'Explorativer Stream; Chemie-LDS als Disziplinkontrolle.',
kick_curr: 'Curriculum', curr_title: 'Curriculum-Analyse', curr_sub: 'Abdeckung: NRW 12,7 % → CN 95,4 %. Drei konkurrierende Erklärungen — Granularität (sicherste) passt am besten.',
curr_a_t: 'A · Granularität ✕', curr_a_d: 'Feinere Standards listen mehr Konzepte — als alleinige Ursache verworfen.',
curr_b_t: 'B · Governance ✓', curr_b_d: 'Zentralisierte Systeme decken mehr ab — Hypothese, Paper §8.6.',
curr_c_t: 'C · Gliederung !', curr_c_d: 'Gegliedert vs Gesamtschule — offene Frage.',
kick_cs: 'Erkunden', cs_title: 'Interaktiver CognitiveSpace', cs_sub: 'Mathe-Subgraph: 556 Knoten · 233 gerenderte Links (von 517) · 219 Gruppen.', cs_open: '3D-Graph öffnen →', kick_labs: 'Anfassen', labs_title: 'Mini-Labore', labs_sub: 'Keine Extraseiten: Die Experimente stecken im Text. Methode ausführen, Gegenbeispiel jagen, Limit abschalten.', lab1_t: 'Reproduktions-Labor', lab1_d: 'Fünf Schritte, fünf Regler: Wort alignieren, LDS-Schwelle ziehen, 50 Permutationen laufen lassen, 59er-Roster aufleuchten.', lab2_t: 'Gegenbeispiel-Jagd', lab2_d: 'Acht harte Fälle dreisprachig nebeneinander — mit Urteil, warum sie Claim C nicht kippen.', lab3_t: 'Limit-Schalttafel', lab3_d: 'Sechs Limits als Schalter: eines abschalten und zusehen, welche Befunde verblassen — plus die Fehldeutung.', lab_open: 'Öffnen →',
kick_paper: 'Paper', paper_title: 'Paper', paper_sub: 'Neun Kernkapitel (~161KB) + PDF (243KB). Anhang W ist explorativ und außerhalb der Begutachtungs-Evidenz.', paper_pdf: 'PDF laden',
kick_open: 'Open Science', open_title: 'Open Science', open_sub: 'Code, Daten, Figuren — und Kontakt.',
open_code_t: 'Code', open_code_d: '84 pytest-Suite; Reproduktions-Guide in Submission-Docs; Gewichtsvektoren via GitHub Release.',
open_data_t: 'Datensatz', open_data_d: '68 Mathe-Extraktionen + lds_c-Messungen; PII aus Submission-Paket ausgeschlossen.',
open_contact_t: 'Kontakt', open_contact_d: 'Via Schulbetreuung (s. Ethik-Consent). Reviews und Zweitr Ratings willkommen.',
footer_note: 'Detailtabelle im v1-Archiv.',
prov_fc_sum: 'Gegenbeispiele: 8 härteste dreisprachige Treffer (Schublade)',
prov_fc_why: 'Warum diese Schublade: das sind die 8 ähnlichsten dreisprachigen Mathe-Gruppen aus data/math_extractions/merged/merged_concepts.json — könnte ein einzelnes geteiltes Konzept Claim C kippen, wäre es eines von diesen.',
cx_1: '[concepts#45] Skalarprodukt / inner product / 内积 · Refs 4 (de 2, en 1, zh 1) — Aliase „Skalarprodukt, dot product, inner product, 点积“. Urteil: Ein geteiltes Knotenlabel lässt die Kantenstruktur unberührt und kann den LDS-K-Split (Spread 0,419) nicht schließen.',
cx_2: '[concepts#52] Ableitung / derivative / 导数 · Refs 4 (de 1, en 2, zh 1) — Aliase „Ableitung, Derivative, Differentialquotient, Differenzialquotient, derivative, derivative function, differential coefficient, 导函数, 微商“. Urteil: Claim C mittelt über 219 Gruppen, ein alignierter Analysis-Kernbegriff bewegt den Korpus-Mittelwert allein praktisch nicht.',
cx_3: '[concepts#54] Funktion / function / 函数 · Refs 5 (de 1, en 2, zh 2) — Aliase „Function, Funktion, function“. Urteil: Genau diese Label-Artefakt-Klasse wurde per T1-Dekontamination falsifiziert (0,556 → 0,020); sie erneut zu zählen, würde die widerlegte Nähe doppelt zählen.',
cx_4: '[concepts#43] Kern / kernel, null space / 核, 零空间 (线性变换的核) · Refs 3 (de 1, en 1, zh 1) — Aliase „Kern, kernel, null space, 核, 零空间“. Urteil: Das harte Matching vergütet dieses Synonymcluster bereits innerhalb der 0,519 — es spricht innerhalb der Behauptung, nicht gegen sie.',
cx_5: '[concepts#29] charakteristische Gleichung / characteristic equation / 特征方程 · Refs 4 (de 1, en 1, zh 2) — Aliase „characteristic equation, charakteristische Gleichung“. Urteil: Tier-2-Vektoren alignieren auch dieses Trio, komprimieren aber alle Paare auf 0,48–0,52 (Spread 0,0445) — Vektoren reproduzieren den Lehrbuch-Split in keine Richtung.',
cx_6: '[concepts#12] Vektor / vector / 向量 · Refs 4 (de 1, en 2, zh 1) — Aliase „Vektor, vector“. Urteil: Ein universelles Lineare-Algebra-Lehnwort erklärt Vokabelüberlapp, aber keine Konvergenz der Relationsgraphen, die LDS-K misst.',
cx_7: '[concepts#53] Grenzwert / limit / 极限 · Refs 4 (de 1, en 2, zh 1) — Aliase „Grenzwert, Limes, Limit, limit“. Urteil: Knoten-Einigkeit im Analysiskern ist mit zh-de-Kantendivergenz auf Korpusebene voll vereinbar.',
cx_8: '[concepts#42] lineare Abbildung / linear transformation / 线性变换, 线性映射 · Refs 3 (de 1, en 1, zh 1) — Aliase „linear transformation, lineare Abbildung, 线性映射“. Urteil: Ein sauberes Tripel bei 219 alignierten vs 359 unalignierten Gruppen kippt keine Korpusstatistik mit 59/59 signifikanten Permutationsläufen.',
prov_fc_chain: 'Zahlenkette: Tier-1-Lehrbuch-LDS-K 0,519 / 0,933 / 0,938 (src/scoring.py:122; research/consensus_v4_20260916.json) · T1-Dekontamination 0,556 → 0,020 · Tier-2-Vektoren 0,4804 / 0,5249 / 0,4888, Spread 0,0445 vs Lehrbuch-Spread 0,419 · Gruppen data/math_extractions/merged/merged_concepts.json Concepts #12, #29, #42, #43, #45, #52, #53, #54 (Ref-Zahlen je Sprache aus je cross_references-Array).',
prov_fc_src: 'Quelle: Merge-Datei data/math_extractions/merged/merged_concepts.json · Code und Daten <a href="https://github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph">github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph</a> — nur frozen Zahlen, hier nichts neuberechnet.',
limsw_link: 'schalt mich ab',
limsw_warn1: 'Fehldeutung bei abgeschaltet: Querverweise wirken gratis, der CDS-Boden (0,271 → 0,073) liest sich dichter als er ist — Befunde A, B, C bleiben preliminary, nie stärker.',
limsw_warn2: 'Fehldeutung bei abgeschaltet: zh-de 0,519 liest sich als echte Konvergenz — konstruktionsbedingt bestraft, Sensitivität einstellig, Claim C behält seinen Split.',
limsw_warn3: 'Fehldeutung bei abgeschaltet: Die N=8-Pilotform (0,704/0,727/0,751) liest sich als Evidenz — Platzhalter bis N=30, Befunde D und E bleiben Form.',
limsw_warn4: 'Fehldeutung bei abgeschaltet: Einzelwerte lesen sich als Konstanten — bei ≈27–41 % Run-Divergenz sind es Schnappschüsse mit Band, A, B, C behalten ihre Bänder.',
limsw_warn5: 'Fehldeutung bei abgeschaltet: Gemischte Voten lesen sich als Trend — zwei Schwellen-Skalen bleiben getrennt, Inter-Mittel über Refills unvergleichbar, A und B zeigen keinen Trend.',
limsw_warn6: 'Fehldeutung bei abgeschaltet: Pro-Split-F1 liest sich solide — 92 Gold-Labels decken nur Gesamt-F1, Deutsch-Mathe-F1 (0,506) hochvariabel, C und E bleiben im Gesamt-Scope.',
curr_ev_a: 'Evidenzbalken: NRW-Boden 12,7 % — feine Standards allein erklären die Lücke nicht (als alleinige Ursache verworfen).',
curr_ev_b: 'Evidenzbalken: CN-Decke 95,4 % — zentralisierte Abdeckungshypothese, Paper §8.6.',
curr_ev_c: 'Evidenzskala 12,7 % → 95,4 % — gegliedert vs Gesamtschule bleibt offene Frage.'
},
zh: {
page_title: 'LinguaGraph — 跨语言知识结构分析',
nav_home: '顶部', nav_validation: '证据', nav_findings: '发现', nav_method: '方法', nav_limits: '局限', nav_sources: '来源', nav_curriculum: '课程', nav_cogspace: '3D 图', nav_labs: '迷你实验室', nav_paper: '论文', nav_open: '开放科学',
hero_kicker: 'BWKI 2026 · 多语言 AI 审计',
hero_title: '不同语言如何组织<em>相同的知识？</em>',
hero_sub: '教科书知识图谱（中、德、英）对照开放权重向量基线——每个数字旁边都印着它的局限。',
stat_rep: '复刻运行 / 模型（文件实情 62/57/186）', stat_graph: '节点 · 关系 · 对齐组（渲染 233）',
stat_f1: '社会 ≈0.94 Developing · 独立 harness ≈0.65 · 盲审待补',
hero_scope: 'frozen＝可引用 · placeholder＝只有形状、无显著性 · pending＝尚未测量。本页没有任何自我升级。',
cta_evidence: '看证据 →', cta_findings: '发现 A–E', cta_3d: '3D 知识图',
kick_evidence: '证据', validation_title: '验证', validation_sub: '先建立信任：查了什么、多少数据、什么局限。',
val_gold_t: '金标：92', val_gold_d: '20 手标数学（Mature C9a）＋ 72 机播社会（Developing C9b，agent 面板已审，人审待补）。',
tag_developing: 'Developing', val_bench_t: '抽取基准：19 模型', val_bench_d: 'F1 范围 0.55–0.67，只用于选抽取模型——绝不用于语言结论。',
val_roster_t: '复刻名录：59＋26', val_roster_d: '59 完整运行（54 模型，中德全部显著）＋ 26 收集中（含 qwen-max n=26/30：搁置、2 稀疏边界、1 隔离）。文件实情 62/57/186。',
val_margin_t: '边际：59/59，p<0.01', val_margin_d: '500 置换；177 中 9 个含 EN 不显著。西方 11/11（0.155；去 luna 10/10，0.148），中国 48/48（0.130）——作厂商比较则效力不足。置换文件实情 62/62。',
kick_findings: '发现', findings_title: '发现 A–E', findings_sub: '五个结论，各带局限。未声明前均为 Preliminary。',
fa_t: 'A · 密度早峰', fa_lead: '课程图谱在初中加密、高中变疏（CDS 0.271→0.073，3.7×）。',
fa_frozen: '冻结快照：2026-06 密集管线（574 节点代，密集代码已丢失）。保持冻结、永不重算——见取证注记。',
fb_t: 'B · 层级很浅', fb_lead: '概念深度 ≤8（数学 ≤8）；83% 概念是层级根。', fb_frozen: '冻结快照，与 A 同源。',
fc_t: 'C · 语言分离结构', fc_lead: '教科书 LDS-K：中德 0.519 远低于含英 ≈0.93（0.933/0.938）。原始中德接近已被证伪为标签伪影（T1 去污 0.556→0.020）。',
fc_tier_sum: 'Two-Tier 对照：向量（不）显示什么',
fc_tier_d: '开放权重嵌入（nomic-embed-text-v1.5，768 维，934 词）把三对全压进 0.48–0.52（spread 0.0445），复现不了教科书分裂（spread 0.419）。只比序，不比值。向量是 control 基线，绝不是证据。',
fd_t: 'D · 体制覆盖各异', fd_lead: '教科书-课程覆盖差异巨大——粒度（最稳解读）与治理（假设）都拟合。',
fe_t: 'E · 人类分不开（被试间）', fe_lead: 'N=15 证伪被试间 ΔLDS＞0（人类 LDS-C≈split-half 地板）；LLM 被试内边际（+0.08–0.09）说明信号存在。早期模拟比较已撤回。',
fe_probe_sum: '人文证伪探针（只单向）',
fe_probe_d: '独立人文切片能削弱"课程特异" claim，但永远证实不了数学结论。Pass：数学分、人文不分→课程特异。Alarm：都分→降级"跨域共享"。现状：pilot N=8（0.704/0.727/0.751）占位——不报 pass/alarm。',
kick_method: '方法', method_title: '五步方法', method_sub: '抽取 → 对齐 → 测量（LDS）→ 零假设检验（500 置换）→ 复刻（59 模型）。',
m1_t: '1 · 抽取', m1_d: '68 教科书文件 → 741 概念 / 665 关系，temperature=0，多模型审计。',
m2_t: '2 · 对齐', m2_d: '219 三语组；硬匹配（小写、ß→ss、同义词表）。对不上就保持不对上。',
m3_t: '3 · 测量', m3_d: 'LDS＝1−mean（GED 相似、节点/边 Jaccard）。冻结：0.519/0.933/0.938。',
m4_t: '4 · 零检验', m4_d: '500 标签置换；p<0.004 是分辨率极限（1/500），不是调参。中德 59/59 通过，边际地板 0.033。',
m5_t: '5 · 复刻', m5_d: '同一 P1 协议 59 测量（54 模型）：多为 DashScope＋裸 host/Kilo/Cohere/NIM/Cloudflare/LM-Studio/opencode-go。可用性样本，非预注册矩阵。',
method_prov: '出处：HF 模型 SHA 是今日 HEAD，不是实验 pin；served revision 未验证；本地 phi 是社区量化版（快照＋附录 W）。',
prov_m1_btn: '显示 A/B 两轮', prov_m1_out: 'temperature=0，两轮：一致 0.59–0.73，分歧 27–41%。单轮值只是快照。', prov_m1_sum: '出处：抽取', prov_m1_why: '为什么：temperature=0 并不确定——单轮撑不起任何数字。', prov_m1_chain: 'data/math_extractions/merged/merged_concepts.json → scripts/math_graph_pipeline/merge_extractions.py → data/math_extractions/merged/pipeline_snapshot.json → research/numbers_ssot_20260916.json · frozen_figures（556 节点 / 517 关系 / 219 组）。',
prov_m2_sum: '出处：对齐', prov_m2_why: '为什么：硬匹配是看得见的规则——对不上就保持不对上。', prov_m2_chain: 'data/math_extractions/merged/aligned_data.json（total_aligned_groups 219）→ scripts/math_graph_pipeline/align_languages.py → manifest.json（alignment.aligned_groups 219）→ SSOT frozen_figures（219 组）。',
prov_m3_lab: '拖动，松开即回冻结值', prov_m3_sum: '出处：测量', prov_m3_why: '为什么：LDS 是公式、不是拟合——值是钉死的。', prov_m3_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/reproduce_lds_binary.py → research/reproduce_headline_20260916.json（claim＝recompute 0.519）→ SSOT lds_k_tier1（0.519 / 0.933 / 0.938）。',
prov_m4_btn: '跑 50 次置换', prov_m4_note: '零假设示意（示出 50/500）；p<0.004 是分辨率 1/500，边际地板 0.033。中德 59/59。', prov_m4_sum: '出处：零检验', prov_m4_why: '为什么：p<0.004 是分辨率极限、不是调参——再多置换也改不了它。', prov_m4_chain: 'data/math_extractions/merged/aligned_data.json → scripts/figures/fig4_null_model.py → research/numbers_ssot_20260916.json → 字段 macro_perm（n_perm 500，p 0.004，floor 0.033）。',
prov_m5_btn: '切换：中德 / 含英', prov_m5_a: '中德：59/59——全绿。', prov_m5_b: '含英：177 检验，9 个标 n.s.。', prov_m5_sum: '出处：复刻', prov_m5_why: '为什么：59 次同协议复刻把信号（中德 59/59）和噪声（含英 9/177 n.s.）分开。', prov_m5_chain: 'manifest.json（pipeline_version 2.0）→ scripts/run_dashscope_batch.py → research/numbers_ssot_20260916.json → 字段 replication（59 测量 / 54 模型 / 177 检验，9/177 n.s.）。',
kick_limits: '局限', limits_title: '局限', limits_sub: '结论之前，先看全部局限。不静默升级。',
l1_t: '切分边界', l1_d: '按节切分；跨节指代计 dangling。偏倚单向且保守。',
l2_t: '硬匹配惩罚', l2_d: '同义异写天然被罚；敏感性是个位数。',
l3_t: '标注稀疏', l3_d: '人类 pilot N=8 只是形状占位；效力设计是 N=30。对齐 219 vs 未对齐 359。',
l4_t: 'temperature=0 也不确定', l4_d: '集成自一致仅 0.59–0.73（约 27–41% 轮间分歧）。单次值都是带波动带的快照。',
l5_t: '快照不稳定', l5_d: '投票总数混了两种阈值刻度，必须拆开展示；跨轮 inter 均值不可比——不报趋势。',
l6_t: '样本小', l6_d: '92 金标够估总体 F1，不够分语言分领域。德国数学 F1（0.506）方差大。',
kick_sources: '来源', sources_title: '来源', sources_sub: '204 教科书：32 数学 · 83 物理 · 89 化学。详表见 v1 存档。',
src_math_t: '数学 · 32', src_math_d: '中/德/英/美教科书，按节 JSON。',
src_phys_t: '物理 · 83', src_phys_d: '探索流；物理 LDS 作学科对照。',
src_chem_t: '化学 · 89', src_chem_d: '探索流；化学 LDS 作学科对照。',
kick_curr: '课程', curr_title: '课程分析', curr_sub: '覆盖率：北威 12.7%→中国 95.4%。三个竞争解释——粒度（最稳）最拟合。',
curr_a_t: 'A · 粒度 ✕', curr_a_d: '细标准列更多概念——否决为唯一原因。',
curr_b_t: 'B · 治理 ✓', curr_b_d: '集权体制覆盖更多——假设，论文 §8.6。',
curr_c_t: 'C · 分流 !', curr_c_d: '分轨 vs 综合——开放问题。',
kick_cs: '探索', cs_title: '交互式 CognitiveSpace', cs_sub: '数学子图：556 节点 · 233 渲染边（共 517）· 219 组。', cs_open: '打开 3D 图 →', kick_labs: '上手', labs_title: '迷你实验室', labs_sub: '无独立页面：实验嵌在正文里。跑方法、打反例、关限制。', lab1_t: '复算实验室', lab1_d: '五步五个控件：对齐单词、拖阈值、跑 50 次置换、点亮 59 名录。', lab2_t: '反例猎人', lab2_d: '八个硬茬三语并排——附裁决：推不翻结论 C。', lab3_t: '限制开关板', lab3_d: '六条限制开关：关一条看哪些发现变暗——附误读警告。', lab_open: '打开 →', 
kick_paper: '论文', paper_title: '论文', paper_sub: '九个核心章（~161KB）＋ PDF（243KB）。附录 W 是探索性的，不在评审证据内。', paper_pdf: '下载 PDF',
kick_open: '开放科学', open_title: '开放科学', open_sub: '代码、数据、图表——和联系方式。',
open_code_t: '代码', open_code_d: '84 pytest 套件；提交文档有复现指南；权重向量走 GitHub Release。',
open_data_t: '数据', open_data_d: '68 数学抽取＋lds_c 测量；PII 不进提交包。',
open_contact_t: '联系', open_contact_d: '经学校导师（见伦理 consent）。欢迎评审与二评。',
footer_note: '详表见 v1 存档。',
prov_fc_sum: '反例：8 个最硬的三语对齐组（抽屉）',
prov_fc_why: '为什么设这个抽屉：这是合并文件 data/math_extractions/merged/merged_concepts.json 里跨语言最相似的 8 个数学组——如果某个共享概念能推翻结论 C，最可能就是其中之一。',
cx_1: '[concepts#45] Skalarprodukt / inner product / 内积 · 引用 4（de 2、en 1、zh 1）——别名"Skalarprodukt, dot product, inner product, 点积"。裁决：共享的节点标签碰不到边结构，关不上 LDS-K 分裂（spread 0.419）。',
cx_2: '[concepts#52] Ableitung / derivative / 导数 · 引用 4（de 1、en 2、zh 1）——别名"Ableitung, Derivative, Differentialquotient, Differenzialquotient, derivative, derivative function, differential coefficient, 导函数, 微商"。裁决：结论 C 是 219 组的平均，一个对齐的微积分核心词搬不动全库均值。',
cx_3: '[concepts#54] Funktion / function / 函数 · 引用 5（de 1、en 2、zh 2）——别名"Function, Funktion, function"。裁决：这正是 T1 去污已证伪的标签伪影类（0.556→0.020），再数一次等于把证伪的接近重复计算。',
cx_4: '[concepts#43] Kern / kernel, null space / 核, 零空间（线性变换的核）· 引用 3（de 1、en 1、zh 1）——别名"Kern, kernel, null space, 核, 零空间"。裁决：硬匹配已在 0.519 内部给这组同义词加过分，它在 claim 里面，不在对立面。',
cx_5: '[concepts#29] charakteristische Gleichung / characteristic equation / 特征方程 · 引用 4（de 1、en 1、zh 2）——别名"characteristic equation, charakteristische Gleichung"。裁决：Tier-2 向量也对得上这三元组，却把三对全压进 0.48–0.52（spread 0.0445），证明向量两边都复现不了教科书分裂。',
cx_6: '[concepts#12] Vektor / vector / 向量 · 引用 4（de 1、en 2、zh 1）——别名"Vektor, vector"。裁决：通用的线性代数外来词只能解释词汇重叠，解释不了 LDS-K 所测的关系图收敛。',
cx_7: '[concepts#53] Grenzwert / limit / 极限 · 引用 4（de 1、en 2、zh 1）——别名"Grenzwert, Limes, Limit, limit"。裁决：分析核心的节点一致与中德边级分歧在全库层面完全兼容。',
cx_8: '[concepts#42] lineare Abbildung / linear transformation / 线性变换, 线性映射 · 引用 3（de 1、en 1、zh 1）——别名"linear transformation, lineare Abbildung, 线性映射"。裁决：219 对齐 vs 359 未对齐中的一组干净三元组，推不翻 59/59 置换显著的全库统计。',
prov_fc_chain: '数字链：Tier-1 教科书 LDS-K 0.519/0.933/0.938（src/scoring.py:122；research/consensus_v4_20260916.json）· T1 去污 0.556→0.020 · Tier-2 向量 0.4804/0.5249/0.4888，spread 0.0445 vs 教科书 spread 0.419 · 组 data/math_extractions/merged/merged_concepts.json concepts #12、#29、#42、#43、#45、#52、#53、#54（各语言引用数逐条引自 cross_references 数组）。',
prov_fc_src: '来源：合并文件 data/math_extractions/merged/merged_concepts.json · 代码与数据 <a href="https://github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph">github.com/jjjjjjjjnnjnn/BWKI-2026-LinguaGraph</a>——只用 frozen 数字，此处不重算。',
limsw_link: '关掉我',
limsw_warn1: '关掉后的误读：跨节链接看似免费，CDS 地板（0.271→0.073）显得比实际更密——发现 A、B、C 仍是 preliminary，绝不会更强。',
limsw_warn2: '关掉后的误读：中德 0.519 看似真收敛——它是构造性惩罚值、敏感性只有个位数，结论 C 的分裂不变。',
limsw_warn3: '关掉后的误读：N=8 pilot 形状（0.704/0.727/0.751）看似证据——N=30 之前只是占位，发现 D、E 保持只有形状。',
limsw_warn4: '关掉后的误读：单次值看似常量——轮间分歧约 27–41%，它们是带波动带的快照，A、B、C 保留波动带。',
limsw_warn5: '关掉后的误读：混合投票看似趋势——两种阈值刻度必须拆开、跨轮 inter 均值不可比，A、B 不报趋势。',
limsw_warn6: '关掉后的误读：分片 F1 看似稳固——92 金标只够估总体 F1，德国数学 F1（0.506）方差大，C、E 留在总体口径。',
curr_ev_a: '证据条：NRW 地板 12.7%——细标准单独解释不了差距（已否决为唯一原因）。',
curr_ev_b: '证据条：CN 天花板 95.4%——集权覆盖假设，论文 §8.6。',
curr_ev_c: '证据尺 12.7%→95.4%——分轨 vs 综合仍是开放问题。'
} };
