#!/usr/bin/env python3
"""Replicate release.py STEP 4 (data.js export) after 517 re-freeze."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
vis = json.loads((ROOT / "data/math_extractions/merged/visualization_data.json").read_text(encoding="utf-8"))
js = "// CognitiveSpace — 3D Knowledge Graph Data\n"
js += "// Auto-generated by release.py\n"
js += f"// Version: 2.0 | {vis['metadata']['total_nodes']} nodes | {len(vis['links'])} links\n"
js += f"// Generated: {vis['generated_at']}\n\n"
js += "var data = " + json.dumps(vis, ensure_ascii=False, indent=2) + ";\n"
(ROOT / "cognitive-space/web/data.js").write_text(js, encoding="utf-8")
(ROOT / "_deploy/data.js").write_text(js, encoding="utf-8")
print("data.js links:", len(vis["links"]))
