#!/usr/bin/env python3
"""Stage0 helper: emit prereg addendum v1.2 (A11-A17) from frozen v2 cells. Zero API."""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
cells = json.load(open(os.path.join(BASE, "research", "mimo_spark_replication",
                                    "_v2_cells.json"), encoding="utf-8"))
P = os.path.join(BASE, "docs", "osf_preregistration_addendum_v1.2_v2.md")
L = []
A = L.append
A("# OSF Preregistration Addendum v1.2 — Harness v2 (2026-09-18, pre-data)")
A("")
A("Parent: `docs/osf_preregistration_addendum_v1.1_spark.md` (A1–A10, frozen).")
A("This file freezes v2 BEFORE the first v2 API call. v1 (`PROMPT_FROZEN_v1.md`,")
A("SHAs `72c5424f…`/`31b8e6eb…`) stays frozen and valid; no retroactive rescoring.")
A("Anchors (minimax UNAVAILABLE per owner 2026-09-18; Western 5th rater CANCELLED):")
A("`glm-5.2-r4`, `r4-deepseek-v4.1-flash`, `sn-sensenova-6.8-flash-lite` (r4 first, sensenova last).")
A("")
A("## A11. Purpose + non-retroactivity per factor")
A("- F1 CARD (P1): range-match removes known precision penalty; no claim that v1 models are bad.")
A("- F2 LANG (P2): removes contradictory language clause; no claim of model-inherent EN failure until P2 fails.")
A("- P3 BOTH: only cell callable fairer instrument. F4 window/F5 DB-path CUT (F4 audit-proven non-binding; F5 incomparable instrument).")
A("- v1 numbers stay frozen; all v2 comparisons paired same-ID (cell vs archival P0).")
A("")
A("## A12. Frozen cells (full texts + SHAs)")
for cell in ("P0", "P1", "P2", "P3"):
    v = cells[cell]
    A("### %s — system_sha256 `%s`" % (cell, v["system_sha256"]))
    A("`" + v["system"].replace("`", "'") + "`")
    A("### %s — template_sha256 `%s`" % (cell, v["template_sha256"]))
    A("```")
    A(v["template"].replace("{text}", "{text}"))
    A("```")
    A("")
A("Byte-diff attested: P1 = P0 with exactly the cardinality sentence replaced (asserted count==1 in `stage0_v2_cells.py`);")
A("P2 = P0 with system replaced; P3 = P1 template + P2 system. Schema/keys/temp/window/scoring unchanged.")
A("")
A("## A13. Metrics + decision thresholds (paired, A2 denominator fails=0/92)")
A("- F1 CARD (P1−P0 full-92 primary; social-72 + gold_n splits secondary): confirmed iff paired mean dF1 ≥ +0.10, CI excludes 0, pred_n → 2–6, n1-lift > n2-lift. Partial if pred_n falls but dF1 < +0.10. Failed if pred_n stays >8.")
A("- F2 LANG (P2−P0 EN+DE n=56 primary, EN-social n=21 key, zh-spot ±0.05): prompt-bug confirmed iff EN-F1 ~0.00 → >0.30 (paired CI excludes 0) AND EN CJK-frac → <10%. Model-side failure iff EN-F1 <0.10 despite CJK <10%. zh regression >0.05 invalidates fix.")
A("- P3 BOTH (P3−P0 full-92): V2-validated iff social F1 enters 0.40–0.65 (NOT DB 0.939), paired CI excludes 0, CJK <10%, pred_n 2–6. Residual-gap iff P3 <0.25 despite both fixes.")
A("- Power: primary = pooled-92 + social-72; EN-social-21 only for large Δ (≥0.3); math cells + 6-way cells descriptive only; exploratory pairs Bonferroni α≈0.003.")
A("")
A("## A14. Arms x cells + budget cap + gates")
A("- CORE (786 nominal): P1 full-92 ×3 anchors (276) + P3 full-92 ×3 (276) + P2 EN+DE+zh10 ×3 (198) + P0-cal n=12 ×3 (36). Retries → ~860–940.")
A("- 1200-nominal cap. Trim order: E4(qwen, CUT) > E2 > E3-shrink; never cut CORE P1/P3.")
A("- EXTENDED gated: E1 (P3 remaining runnable arms full-92) iff CORE P3 paired lift CI-excludes-0 on ≥2/3 anchors; E3 (temp 0 vs 0.1, glm P3 same-30-IDs, 60 calls) anytime; E2 (P3b paraphrase, glm n=30, 30 calls) iff P3 lift exists, |d|≥0.10 → brittle.")
A("- Smoke per cell×arm: `--max-items 5` (2en+2de+1zh, mixed gold_n); gate ≥4/5 parse-valid AND directional (P1 pred_n<P0; P2 EN-CJK≤P0; P3 both). Fail → investigate, no full launch, deviation log.")
A("- Serial per arm/key (A10); per-ns lock; checkpoint+heartbeat; breaker 5-fail park (A9-5); resume-safe.")
A("")
A("## A15. Quarantine / naming / transport")
A("- Outputs only `research/mimo_spark_replication/t2_v2-<arm>-<cell>.json` (+ stage/prompts/locks with `v2-` prefix).")
A("- FORBIDDEN writes: `t2_<ns>.json` (v1), `data/math_extractions/`, `freeze/`, `data/lds_c/`, `tests/`.")
A("- Per-record provenance: model + endpoint + date + temperature actually used + input_sha256/chars + cell + prompt SHAs + rung + attempts (err-class, no keys). free≠paid / provider≠provider scope stands. Keys in-process from `.env` only.")
A("")
A("## A16. Analysis plan (deterministic, zero extra API)")
A("- Reuse deep-dive pipeline (cell CIs informative cells only, gold_n stratification, pre-declared paired dF1 P1−P0/P2−P0/P3−P0 per anchor, pred_n–F1 Pearson+bins per cell, CJK-frac + per-language means per cell, difficulty n=9 DO-NOT-USE). Bootstrap B=1000 seed 20260918 unchanged.")
A("")
A("## A17. Claim mapping")
A("- P1 lifts strongly → v1 lows were penalty artefacts; C9b stays Developing (blind review pending); C21 refined (v2-partial-repro); C23 hardens (Mature candidate).")
A("- P2 lifts EN → language bug masking; same statuses as P1.")
A("- P3 reaches 0.40–0.65 → dual-harness narrative at fairer instrument; C21 quantitative v2-gap; C23 confirmed, P3 recommended default.")
A("- All fail (P3 <0.25, EN ~0) → mechanisms exhausted, gap looks model/seed (C21 severity up, still Developing); C23 downgraded to hypothesis, mimo-noise line becomes lead.")
A("")
A("Frozen 2026-09-18 BEFORE first v2 call. Any byte-change after = deviation D-Vx. Owner: methods.")
open(P, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("ADDENDUM-WRITTEN", os.path.getsize(P))
