#!/usr/bin/env python3
"""Build STEAM fused viewer graph (math + physics + chemistry).

Reads the three viewer-level sources (the same files index.html loads),
tags every node/link with `discipline`, asserts ID-disjointness, and writes
cognitive-space/web/data_steam.js (var data_steam).

No cross-discipline links: the former hand-picked 10-bridge allowlist was
retired 2026-09-14 (insufficient systematic evidence; archived at
research/steam_bridges_retired_2026-09-14.json). STEAM is a side-by-side
comparison view, not a claim of cross-discipline structure.

SSOT counts: 556 + 367 + 220 = 1143 nodes; 233 + 386 + 215 = 834
intra-discipline links.

Usage: python scripts/build_steam_graph.py
"""
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "cognitive-space" / "web"

SOURCES = [
    ("math", WEB / "data.js"),
    ("physics", WEB / "data_physics.js"),
    ("chemistry", WEB / "data_chemistry.js"),
]


def load_viewer(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"var \w+ = (\{.*\});?\s*$", text, re.S)
    if not m:
        raise ValueError(f"no var payload in {path}")
    return json.loads(m.group(1))


def main() -> int:
    nodes, links = [], []
    seen_ids: dict[str, str] = {}
    stats = {}
    for disc, path in SOURCES:
        data = load_viewer(path)
        ns, ls = data["nodes"], data["links"]
        for n in ns:
            nid = n["id"]
            if nid in seen_ids:
                raise SystemExit(
                    f"ID collision: {nid} in {disc} and {seen_ids[nid]}"
                )
            seen_ids[nid] = disc
            n = dict(n)
            n["discipline"] = disc
            nodes.append(n)
        for lk in ls:
            lk = dict(lk)
            lk["discipline"] = disc
            links.append(lk)
        stats[disc] = {"nodes": len(ns), "links": len(ls)}
        print(f"{disc}: {len(ns)} nodes / {len(ls)} links")

    assert len(nodes) == 1143, f"node count drift: {len(nodes)}"
    assert len(links) == 834, f"link count drift: {len(links)}"

    payload = {
        "version": "steam-v2",
        "disciplines": ["math", "physics", "chemistry"],
        "bridge_count": 0,
        "nodes": nodes,
        "links": links,
        "metadata": {
            "sources": stats,
            "bridges_retired": "2026-09-14: hand-picked 10-bridge allowlist removed "
            "(insufficient systematic evidence); archived at "
            "research/steam_bridges_retired_2026-09-14.json",
        },
    }
    out = WEB / "data_steam.js"
    with io.open(out, "w", encoding="utf-8", newline="") as fh:
        fh.write("// CognitiveSpace — STEAM fused graph (math+physics+chemistry)\n")
        fh.write("// Auto-generated by scripts/build_steam_graph.py — DO NOT EDIT.\n")
        fh.write("var data_steam = ")
        json.dump(payload, fh, ensure_ascii=False)
        fh.write(";\n")

    print(f"OK: {len(nodes)} nodes / {len(links)} links (0 bridges)")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
