#!/usr/bin/env python3
"""Build STEAM fused viewer graph (math + physics + chemistry).

Reads the three viewer-level sources (the same files index.html loads),
tags every node/link with `discipline`, asserts ID-disjointness, adds
frozen cross-discipline bridge links (see BRIDGE_ALLOWLIST), and writes
cognitive-space/web/data_steam.js (var data_steam) + the frozen bridge
dictionary data/steam_bridge_dict.json.

SSOT counts: 556 + 367 + 220 = 1143 nodes; 238 + 386 + 215 = 839
intra-discipline links + len(BRIDGE_ALLOWLIST) bridge links.

Usage: python scripts/build_steam_graph.py
"""
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "cognitive-space" / "web"

SOURCES = [
    ("math", WEB / "data.js"),
    ("physics", WEB / "data_physics.js"),
    ("chemistry", WEB / "data_chemistry.js"),
]

# Frozen bridge allowlist: normalized en-label -> explicit (source_id, target_id).
# Reviewed 2026-09-14: 10 high-confidence shared-concept pairs (thermo laws,
# resonance/SHM/kinematics math-physics, Avogadro/Brownian phys-chem,
# significant figures math-chem). Frozen: edits require re-review + rerun.
BRIDGE_ALLOWLIST = {
    "acceleration": ("math_unmatched_加速度", "physics_mechanics_加速度"),
    "avogadro's number": ("physics_thermo_阿伏伽德罗常数", "chem_阿伏伽德罗常数"),
    "brownian motion": ("physics_thermo_布朗运动", "chem_布朗运动_chem"),
    "first law of thermodynamics": ("physics_thermo_热力学第一定律", "chem_热力学第一定律_chem"),
    "resonance": ("math_calculus_共振", "physics_mechanics_共振"),
    "second law of thermodynamics": ("physics_thermo_热力学第二定律", "chem_热力学第二定律_chem"),
    "significant figures": ("math_unmatched_significant figures", "chem_有效数字"),
    "simple harmonic motion": ("math_calculus_简谐运动", "physics_mechanics_简谐运动"),
    "time": ("math_unmatched_time", "physics_mechanics_时间"),
    "velocity": ("math_calculus_速度", "physics_mechanics_速度"),
}


def load_viewer(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"var \w+ = (\{.*\});?\s*$", text, re.S)
    if not m:
        raise ValueError(f"no var payload in {path}")
    return json.loads(m.group(1))


def main() -> int:
    nodes, links = [], []
    seen_ids: dict[str, str] = {}
    stats = {}
    for disc, path in SOURCES:
        data = load_viewer(path)
        ns, ls = data["nodes"], data["links"]
        for n in ns:
            nid = n["id"]
            if nid in seen_ids:
                raise SystemExit(
                    f"ID collision: {nid} in {disc} and {seen_ids[nid]}"
                )
            seen_ids[nid] = disc
            n = dict(n)
            n["discipline"] = disc
            nodes.append(n)
        for lk in ls:
            lk = dict(lk)
            lk["discipline"] = disc
            lk["cross_discipline"] = False
            links.append(lk)
        stats[disc] = {"nodes": len(ns), "links": len(ls)}
        print(f"{disc}: {len(ns)} nodes / {len(ls)} links")

    by_id = {n["id"]: n for n in nodes}
    bridges = []
    for label, (src, tgt) in BRIDGE_ALLOWLIST.items():
        missing = [i for i in (src, tgt) if i not in by_id]
        if missing:
            raise SystemExit(f"bridge '{label}' references missing ids: {missing}")
        bridges.append(
            {
                "source": src,
                "target": tgt,
                "type": "analogy",
                "importance": 0.9,
                "known": True,
                "evidence": f"STEAM bridge: shared en-label '{label}' (frozen allowlist)",
                "discipline": "cross",
                "cross_discipline": True,
                "inferred": True,
            }
        )
    links.extend(bridges)

    assert len(nodes) == 1143, f"node count drift: {len(nodes)}"
    assert len(links) == 839 + len(bridges), f"link count drift: {len(links)}"
    assert len(bridges) == 10, f"bridge count drift: {len(bridges)}"

    payload = {
        "version": "steam-v1",
        "disciplines": ["math", "physics", "chemistry"],
        "bridge_count": len(bridges),
        "nodes": nodes,
        "links": links,
        "metadata": {"sources": stats, "bridge_allowlist": "data/steam_bridge_dict.json"},
    }
    out = WEB / "data_steam.js"
    with io.open(out, "w", encoding="utf-8", newline="") as fh:
        fh.write("// CognitiveSpace — STEAM fused graph (math+physics+chemistry)\n")
        fh.write("// Auto-generated by scripts/build_steam_graph.py — DO NOT EDIT.\n")
        fh.write("var data_steam = ")
        json.dump(payload, fh, ensure_ascii=False)
        fh.write(";\n")

    bdict = ROOT / "data" / "steam_bridge_dict.json"
    with io.open(bdict, "w", encoding="utf-8", newline="") as fh:
        json.dump(
            {"frozen": "2026-09-14", "bridges": BRIDGE_ALLOWLIST},
            fh,
            ensure_ascii=False,
            indent=2,
        )
        fh.write("\n")

    print(f"OK: {len(nodes)} nodes / {len(links)} links ({len(bridges)} bridges)")
    print(f"wrote {out} + {bdict}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
