#!/usr/bin/env python3
"""
Expand physics_full.json from 87 to 200+ concepts.
Covers: mechanics, thermodynamics, E&M, optics, modern physics, fluid mechanics.
Each language: 10+ publishers, elementary through university.
"""

import json
from pathlib import Path
from datetime import datetime

PROJECT_DIR = Path(__file__).resolve().parent.parent
OUTPUT = PROJECT_DIR / "config" / "expert_graphs" / "physics_full.json"

# ── Publisher catalogs per language ──────────────────────────────────

ZH_PUBLISHERS = {
    "elementary": [
        ("人教版小学科学三年级上", "三年级", "上册"),
        ("人教版小学科学四年级上", "四年级", "上册"),
        ("人教版小学科学五年级上", "五年级", "上册"),
        ("沪教版小学科学三年级", "三年级", ""),
        ("北师大版小学科学四年级", "四年级", ""),
    ],
    "middle": [
        ("人教版初中物理八年级上", "八年级上", ""),
        ("人教版初中物理八年级下", "八年级下", ""),
        ("人教版初中物理九年级全一册", "九年级", ""),
        ("沪科版初中物理八年级", "八年级", ""),
        ("北师大版初中物理八年级", "八年级", ""),
        ("苏科版初中物理八年级", "八年级", ""),
        ("粤教版初中物理八年级", "八年级", ""),
    ],
    "high": [
        ("人教版高中物理必修第一册", "必修1", ""),
        ("人教版高中物理必修第二册", "必修2", ""),
        ("人教版高中物理必修第三册", "必修3", ""),
        ("人教版高中物理选择性必修第一册", "选必1", ""),
        ("人教版高中物理选择性必修第二册", "选必2", ""),
        ("人教版高中物理选择性必修第三册", "选必3", ""),
        ("沪科版高中物理", "全册", ""),
        ("粤教版高中物理", "全册", ""),
        ("鲁科版高中物理", "全册", ""),
    ],
    "college": [
        ("大学物理（马文蔚）", "上册", ""),
        ("大学物理（马文蔚）", "下册", ""),
        ("普通物理学（程守洙）", "上册", ""),
        ("普通物理学（程守洙）", "下册", ""),
        ("力学（漆安慎）", "全册", ""),
        ("电磁学（赵凯华）", "全册", ""),
        ("热学（汪志诚）", "全册", ""),
        ("光学（赵凯华）", "全册", ""),
        ("原子物理学（杨福家）", "全册", ""),
        ("理论力学（梁昆淼）", "全册", ""),
        ("电动力学（郭硕鸿）", "全册", ""),
        ("量子力学（曾谨言）", "全册", ""),
    ],
}

EN_PUBLISHERS = {
    "elementary": [
        ("Khan Academy: Elementary Science", "Grades K-2", "Forces and Motion"),
        ("Khan Academy: Elementary Science", "Grades 3-5", "Energy and Waves"),
        ("National Geographic: Force, Motion, and Simple Machines", "Chapters 1-8", ""),
        ("CK-12: Elementary Physical Science", "Grades 3-5", ""),
    ],
    "middle": [
        ("Khan Academy Physics", "Middle School", "Intro to Physics"),
        ("CK-12: Middle School Physics", "Full", ""),
        ("Pearson: Prentice Hall Science Explorer", "Grade 8", "Physical Science"),
        ("Glencoe: Physics: Principles and Problems", "Chapters 1-10", ""),
        ("Holt: Middle School Science", "Grade 8", ""),
        ("BBC Bitesize: KS3 Physics", "Full", ""),
    ],
    "high": [
        ("AP Physics 1", "Full Curriculum", "Algebra-based"),
        ("AP Physics 2", "Full Curriculum", "Algebra-based"),
        ("AP Physics C: Mechanics", "Full Curriculum", "Calculus-based"),
        ("AP Physics C: E&M", "Full Curriculum", "Calculus-based"),
        ("IB Physics SL/HL", "Full", ""),
        ("IGCSE Physics (0625)", "Full", ""),
        ("GCSE AQA Physics", "Full", ""),
        ("GCSE Edexcel Physics", "Full", ""),
        ("A-Level Physics (AQA)", "Full", ""),
        ("A-Level Physics (OCR)", "Full", ""),
        ("Cambridge IGCSE Physics", "Full", ""),
    ],
    "college": [
        ("Halliday Resnick Walker: Fundamentals of Physics", "Vol. 1", ""),
        ("Halliday Resnick Walker: Fundamentals of Physics", "Vol. 2", ""),
        ("Serway Jewett: Physics for Scientists and Engineers", "Vol. 1", ""),
        ("Serway Jewett: Physics for Scientists and Engineers", "Vol. 2", ""),
        ("Young Freedman: University Physics", "Vol. 1", ""),
        ("Young Freedman: University Physics", "Vol. 2", ""),
        ("Kleintolkroemer: Classical Electrodynamics", "Full", ""),
        ("Griffiths: Introduction to Electrodynamics", "Full", ""),
        ("Kittel: Introduction to Solid State Physics", "Full", ""),
        ("Schrödinger: Quantum Mechanics", "Full", ""),
        ("Landau Lifshitz: Mechanics", "Vol. 1", ""),
        ("Feynman Lectures on Physics", "Vol. 1", ""),
        ("Feynman Lectures on Physics", "Vol. 2", ""),
    ],
}

DE_PUBLISHERS = {
    "elementary": [
        ("Duden: Physik Kompakt", "5.-6. Klasse", ""),
        ("Cornelsen: Physik entdecken", "5. Klasse", ""),
        ("Westermann: Physik", "5. Klasse", ""),
    ],
    "middle": [
        ("Duden: Physik Kompakt", "7.-10. Klasse", ""),
        ("Lambacher Schwere: Physik", "5.-8. Klasse", ""),
        ("Lambacher Schwere: Physik", "8.-10. Klasse erweitert", ""),
        ("Westermann: Physik", "9.-10. Klasse", ""),
        ("Cornelsen: Physik aktiv", "8.-10. Klasse", ""),
        ("Klett: Physik", "8.-10. Klasse", ""),
        ("Auer: Physik", "Realschule", ""),
    ],
    "high": [
        ("Westermann: Physik Oberstufe", "Q11-Q12", ""),
        ("Dorn-Bader: Physik", "Abitur LK", ""),
        ("Kern: Physik", "Abitur LK", ""),
        ("Thieme: Physik", "Abitur", ""),
        ("DUDEN: Physik Abitur", "Gymnasium", ""),
        ("Cornelsen: Physik Oberstufe", "Abiturvorbereitung", ""),
    ],
    "college": [
        ("Tipler: Physik", "Band 1", ""),
        ("Tipler: Physik", "Band 2", ""),
        ("Demtröder: Experimentalphysik", "Band 1", ""),
        ("Demtröder: Experimentalphysik", "Band 2", ""),
        ("Demtröder: Experimentalphysik", "Band 3", ""),
        ("Jackson: Klassische Elektrodynamik", "Full", ""),
        ("Arfken: Mathematical Methods", "Full", ""),
        ("Schiff: Quantenmechanik", "Full", ""),
        ("Greiner: Klassische Mechanik", "Full", ""),
        ("Greiner: Quantenmechanik", "Full", ""),
        ("Greiner: Thermodynamik und Statistische Mechanik", "Full", ""),
    ],
}


def make_ref(lang, publisher, chapter, section):
    return {"textbook": publisher, "language": lang, "chapter": chapter, "section": section}


def concept(name, display, level, labels, refs):
    return {
        "name": f"physics_{name}",
        "display_name": display,
        "category": "concept",
        "level": level,
        "labels": labels,
        "source_references": refs
    }


# ══════════════════════════════════════════════════════════════════════
#  ALL 200+ CONCEPTS
# ══════════════════════════════════════════════════════════════════════

concepts = []

# ──────────────────────────────────────────────────────
# SECTION 1: MECHANICS (Foundation → Advanced)
# ──────────────────────────────────────────────────────

# 1.1 Elementary / Middle school basics
mechanics_basics = [
    ("mechanics_运动", "机械运动", "elementary",
     {"zh": "机械运动", "en": "Mechanical Motion", "de": "Mechanische Bewegung"}),
    ("mechanics_参照系", "参照系", "elementary",
     {"zh": "参照系", "en": "Reference Frame", "de": "Bezugssystem"}),
    ("mechanics_位移", "位移", "elementary",
     {"zh": "位移", "en": "Displacement", "de": "Verschiebung"}),
    ("mechanics_路程", "路程", "elementary",
     {"zh": "路程", "en": "Distance", "de": "Wegstrecke"}),
    ("mechanics_速度", "速度", "elementary",
     {"zh": "速度", "en": "Velocity", "de": "Geschwindigkeit"}),
    ("mechanics_速率", "速率", "elementary",
     {"zh": "速率", "en": "Speed", "de": "Geschwindigkeit (Betragswert)"}),
    ("mechanics_匀速直线运动", "匀速直线运动", "elementary",
     {"zh": "匀速直线运动", "en": "Uniform Linear Motion", "de": "gleichförmige geradlinige Bewegung"}),
    ("mechanics_时间", "时间", "elementary",
     {"zh": "时间", "en": "Time", "de": "Zeit"}),
    ("mechanics_长度测量", "长度测量", "elementary",
     {"zh": "长度测量", "en": "Length Measurement", "de": "Längenmessung"}),
    ("mechanics_时间测量", "时间测量", "elementary",
     {"zh": "时间测量", "en": "Time Measurement", "de": "Zeitmessung"}),
]

# 1.2 Middle school forces
mechanics_forces_mid = [
    ("mechanics_力", "力", "middle",
     {"zh": "力", "en": "Force", "de": "Kraft"}),
    ("mechanics_重力", "重力", "middle",
     {"zh": "重力", "en": "Gravity", "de": "Gravitationskraft"}),
    ("mechanics_弹力", "弹力", "middle",
     {"zh": "弹力", "en": "Elastic Force", "de": "Federkraft"}),
    ("mechanics_摩擦力", "摩擦力", "middle",
     {"zh": "摩擦力", "en": "Friction", "de": "Reibungskraft"}),
    ("mechanics_质量", "质量", "middle",
     {"zh": "质量", "en": "Mass", "de": "Masse"}),
    ("mechanics_密度", "密度", "middle",
     {"zh": "密度", "en": "Density", "de": "Dichte"}),
    ("mechanics_二力平衡", "二力平衡", "middle",
     {"zh": "二力平衡", "en": "Two-Force Equilibrium", "de": "Kraftgleichgewicht"}),
    ("mechanics_惯性", "惯性", "middle",
     {"zh": "惯性", "en": "Inertia", "de": "Trägheit"}),
    ("mechanics_简单机械", "简单机械", "middle",
     {"zh": "简单机械", "en": "Simple Machines", "de": "Einfache Maschinen"}),
    ("mechanics_杠杆", "杠杆", "middle",
     {"zh": "杠杆", "en": "Lever", "de": "Hebel"}),
    ("mechanics_滑轮", "滑轮", "middle",
     {"zh": "滑轮", "en": "Pulley", "de": "Rolle"}),
    ("mechanics_功", "功", "middle",
     {"zh": "功", "en": "Work", "de": "Arbeit"}),
    ("mechanics_功率", "功率", "middle",
     {"zh": "功率", "en": "Power", "de": "Leistung"}),
    ("mechanics_机械能", "机械能", "middle",
     {"zh": "机械能", "en": "Mechanical Energy", "de": "Mechanische Energie"}),
    ("mechanics_动能", "动能", "middle",
     {"zh": "动能", "en": "Kinetic Energy", "de": "Kinetische Energie"}),
    ("mechanics_势能", "势能", "middle",
     {"zh": "势能", "en": "Potential Energy", "de": "Potentielle Energie"}),
    ("mechanics_能量转化", "能量转化与守恒", "middle",
     {"zh": "能量转化与守恒", "en": "Energy Transformation", "de": "Energieumwandlung"}),
    ("mechanics_压强", "压强", "middle",
     {"zh": "压强", "en": "Pressure", "de": "Druck"}),
    ("mechanics_大气压强", "大气压强", "middle",
     {"zh": "大气压强", "en": "Atmospheric Pressure", "de": "Luftdruck"}),
    ("mechanics_浮力", "浮力", "middle",
     {"zh": "浮力", "en": "Buoyancy", "de": "Auftrieb"}),
    ("mechanics_阿基米德原理", "阿基米德原理", "middle",
     {"zh": "阿基米德原理", "en": "Archimedes' Principle", "de": "Archimedisches Prinzip"}),
    ("mechanics_流体压强", "流体压强与流速的关系", "middle",
     {"zh": "流体压强与流速的关系", "en": "Bernoulli's Principle", "de": "Bernoulli-Gleichung"})],

# 1.3 High school mechanics
mechanics_high = [
    ("mechanics_加速度", "加速度", "high",
     {"zh": "加速度", "en": "Acceleration", "de": "Beschleunigung"}),
    ("mechanics_匀变速直线运动", "匀变速直线运动", "high",
     {"zh": "匀变速直线运动", "en": "Uniformly Accelerated Motion", "de": "gleichmäßig beschleunigte Bewegung"}),
    ("mechanics_自由落体", "自由落体运动", "high",
     {"zh": "自由落体运动", "en": "Free Fall", "de": "Freier Fall"}),
    ("mechanics_竖直上抛", "竖直上抛运动", "high",
     {"zh": "竖直上抛运动", "en": "Vertical Projectile Motion", "de": "Vertikaler Wurf"}),
    ("mechanics_平抛运动", "平抛运动", "high",
     {"zh": "平抛运动", "en": "Horizontal Projectile", "de": "Wagrechter Wurf"}),
    ("mechanics_斜抛运动", "斜抛运动", "high",
     {"zh": "斜抛运动", "en": "Oblique Projectile", "de": "Schiefer Wurf"}),
    ("mechanics_运动的合成与分解", "运动的合成与分解", "high",
     {"zh": "运动的合成与分解", "en": "Composition of Motion", "de": "Zusammensetzung von Bewegungen"}),
    ("mechanics_牛顿第一定律", "牛顿第一定律", "high",
     {"zh": "牛顿第一定律", "en": "Newton's First Law", "de": "1. Newtonsches Gesetz"}),
    ("mechanics_牛顿第二定律", "牛顿第二定律", "high",
     {"zh": "牛顿第二定律", "en": "Newton's Second Law", "de": "2. Newtonsches Gesetz"}),
    ("mechanics_牛顿第三定律", "牛顿第三定律", "high",
     {"zh": "牛顿第三定律", "en": "Newton's Third Law", "de": "3. Newtonsches Gesetz"}),
    ("mechanics_动量", "动量", "high",
     {"zh": "动量", "en": "Momentum", "de": "Impuls"}),
    ("mechanics_动量守恒", "动量守恒定律", "high",
     {"zh": "动量守恒定律", "en": "Conservation of Momentum", "de": "Impulserhaltungssatz"}),
    ("mechanics_碰撞", "碰撞", "high",
     {"zh": "碰撞", "en": "Collisions", "de": "Stoß"}),
    ("mechanics_弹性碰撞", "弹性碰撞", "high",
     {"zh": "弹性碰撞", "en": "Elastic Collision", "de": "Elastischer Stoß"}),
    ("mechanics_非弹性碰撞", "非弹性碰撞", "high",
     {"zh": "非弹性碰撞", "en": "Inelastic Collision", "de": "Unelastischer Stoß"}),
    ("mechanics_完全非弹性碰撞", "完全非弹性碰撞", "high",
     {"zh": "完全非弹性碰撞", "en": "Perfectly Inelastic Collision", "de": "Vollkommen unelastischer Stoß"}),
    ("mechanics_冲量", "冲量", "high",
     {"zh": "冲量", "en": "Impulse", "de": "Impuls (Stoß)"}),
    ("mechanics_动能定理", "动能定理", "high",
     {"zh": "动能定理", "en": "Work-Energy Theorem", "de": "Arbeit-Energie-Theorem"}),
    ("mechanics_机械能守恒", "机械能守恒定律", "high",
     {"zh": "机械能守恒定律", "en": "Conservation of Mechanical Energy", "de": "Erhaltung mechanischer Energie"}),
    ("mechanics_能量守恒", "能量守恒定律", "high",
     {"zh": "能量守恒定律", "en": "Conservation of Energy", "de": "Energieerhaltungssatz"}),
    ("mechanics_万有引力", "万有引力定律", "high",
     {"zh": "万有引力定律", "en": "Newton's Law of Gravitation", "de": "Universelles Gravitationsgesetz"}),
    ("mechanics_开普勒第一定律", "开普勒第一定律", "high",
     {"zh": "开普勒第一定律", "en": "Kepler's First Law", "de": "Keplers 1. Gesetz"}),
    ("mechanics_开普勒第二定律", "开普勒第二定律", "high",
     {"zh": "开普勒第二定律", "en": "Kepler's Second Law", "de": "Keplers 2. Gesetz"}),
    ("mechanics_开普勒第三定律", "开普勒第三定律", "high",
     {"zh": "开普勒第三定律", "en": "Kepler's Third Law", "de": "Keplers 3. Gesetz"}),
    ("mechanics_宇宙速度", "宇宙速度", "high",
     {"zh": "宇宙速度", "en": "Cosmic Velocities", "de": "Kosmische Geschwindigkeiten"}),
    ("mechanics_卫星运动", "人造卫星运动", "high",
     {"zh": "人造卫星运动", "en": "Satellite Motion", "de": "Satellitenbewegung"}),
    ("mechanics_圆周运动", "圆周运动", "high",
     {"zh": "圆周运动", "en": "Circular Motion", "de": "Kreisbewegung"}),
    ("mechanics_向心加速度", "向心加速度", "high",
     {"zh": "向心加速度", "en": "Centripetal Acceleration", "de": "Zentripetalbeschleunigung"}),
    ("mechanics_向心力", "向心力", "high",
     {"zh": "向心力", "en": "Centripetal Force", "de": "Zentripetalkraft"}),
    ("mechanics_离心现象", "离心现象", "high",
     {"zh": "离心现象", "en": "Centrifugal Phenomena", "de": "Zentrifugalphänomene"}),
    ("mechanics_简谐运动", "简谐运动", "high",
     {"zh": "简谐运动", "en": "Simple Harmonic Motion", "de": "Harmonische Schwingung"}),
    ("mechanics_单摆", "单摆", "high",
     {"zh": "单摆", "en": "Simple Pendulum", "de": "Einfaches Pendel"}),
    ("mechanics_弹簧振子", "弹簧振子", "high",
     {"zh": "弹簧振子", "en": "Spring-Mass System", "de": "Federpendel"}),
    ("mechanics_振动图像", "振动图像", "high",
     {"zh": "振动图像", "en": "Oscillation Graph", "de": "Schwingungsbild"}),
    ("mechanics_受迫振动", "受迫振动", "high",
     {"zh": "受迫振动", "en": "Forced Oscillation", "de": "Erzwungene Schwingung"}),
    ("mechanics_共振", "共振", "high",
     {"zh": "共振", "en": "Resonance", "de": "Resonanz"}),
    ("mechanics_机械波", "机械波", "high",
     {"zh": "机械波", "en": "Mechanical Waves", "de": "Mechanische Wellen"}),
    ("mechanics_横波", "横波", "high",
     {"zh": "横波", "en": "Transverse Wave", "de": "Transversalwelle"}),
    ("mechanics_纵波", "纵波", "high",
     {"zh": "纵波", "en": "Longitudinal Wave", "de": "Longitudinalwelle"}),
    ("mechanics_波长", "波长", "high",
     {"zh": "波长", "en": "Wavelength", "de": "Wellenlänge"}),
    ("mechanics_频率", "频率", "high",
     {"zh": "频率", "en": "Frequency", "de": "Frequenz"}),
    ("mechanics_波速", "波速", "high",
     {"zh": "波速", "en": "Wave Speed", "de": "Wellengeschwindigkeit"}),
    ("mechanics_波的叠加", "波的叠加原理", "high",
     {"zh": "波的叠加原理", "en": "Superposition of Waves", "de": "Superpositionsprinzip"}),
    ("mechanics_波的干涉", "波的干涉", "high",
     {"zh": "波的干涉", "en": "Wave Interference", "de": "Welleninterferenz"}),
    ("mechanics_波的衍射", "波的衍射", "high",
     {"zh": "波的衍射", "en": "Wave Diffraction", "de": "Beugung"}),
    ("mechanics_多普勒效应", "多普勒效应", "high",
     {"zh": "多普勒效应", "en": "Doppler Effect", "de": "Dopplereffekt"}),
    ("mechanics_驻波", "驻波", "high",
     {"zh": "驻波", "en": "Standing Wave", "de": "Stehende Welle"}),
    ("mechanics_声波", "声波", "middle",
     {"zh": "声波", "en": "Sound Wave", "de": "Schallwelle"}),
    ("mechanics_音调", "音调", "middle",
     {"zh": "音调", "en": "Pitch", "de": "Tonhöhe"}),
    ("mechanics_响度", "响度", "middle",
     {"zh": "响度", "en": "Loudness", "de": "Lautstärke"}),
    ("mechanics_音色", "音色", "middle",
     {"zh": "音色", "en": "Timbre", "de": "Klangfarbe"}),
    ("mechanics_回声", "回声", "middle",
     {"zh": "回声", "en": "Echo", "de": "Echo"}),
    ("mechanics_声速", "声速", "middle",
     {"zh": "声速", "en": "Speed of Sound", "de": "Schallgeschwindigkeit"}),
]

# 1.4 College mechanics
mechanics_college = [
    ("mechanics_力矩", "力矩", "college",
     {"zh": "力矩", "en": "Torque", "de": "Drehmoment"}),
    ("mechanics_转动惯量", "转动惯量", "college",
     {"zh": "转动惯量", "en": "Moment of Inertia", "de": "Trägheitsmoment"}),
    ("mechanics_角动量", "角动量", "college",
     {"zh": "角动量", "en": "Angular Momentum", "de": "Drehimpuls"}),
    ("mechanics_角动量守恒", "角动量守恒", "college",
     {"zh": "角动量守恒", "en": "Conservation of Angular Momentum", "de": "Drehimpulserhaltung"}),
    ("mechanics_转动动能", "转动动能", "college",
     {"zh": "转动动能", "en": "Rotational Kinetic Energy", "de": "Rotationsenergie"}),
    ("mechanics_刚体定轴转动", "刚体定轴转动", "college",
     {"zh": "刚体定轴转动", "en": "Rotation about a Fixed Axis", "de": "Drehung um eine feste Achse"}),
    ("mechanics_刚体平面运动", "刚体平面运动", "college",
     {"zh": "刚体平面运动", "en": "Plane Motion of Rigid Bodies", "de": "Ebene Bewegung starrer Körper"}),
    ("mechanics_滚动摩擦", "滚动摩擦", "college",
     {"zh": "滚动摩擦", "en": "Rolling Friction", "de": "Rollreibung"}),
    ("mechanics_非惯性系", "非惯性参考系", "college",
     {"zh": "非惯性参考系", "en": "Non-Inertial Frame", "de": "Nichtinertialsystem"}),
    ("mechanics_科里奥利力", "科里奥利力", "college",
     {"zh": "科里奥利力", "en": "Coriolis Force", "de": "Corioliskraft"}),
    ("mechanics_虚功原理", "虚功原理", "college",
     {"zh": "虚功原理", "en": "Principle of Virtual Work", "de": "Prinzip der virtuellen Arbeit"}),
    ("mechanics_拉格朗日方程", "拉格朗日方程", "college",
     {"zh": "拉格朗日方程", "en": "Lagrange's Equations", "de": "Lagrange-Gleichungen"}),
    ("mechanics_哈密顿方程", "哈密顿方程", "college",
     {"zh": "哈密顿方程", "en": "Hamilton's Equations", "de": "Hamiltonsche Gleichungen"}),
    ("mechanics_弹性势能", "弹性势能", "college",
     {"zh": "弹性势能", "en": "Elastic Potential Energy", "de": "Elastische potentielle Energie"}),
    ("mechanics_保守力", "保守力", "college",
     {"zh": "保守力", "en": "Conservative Force", "de": "Konservative Kraft"}),
    ("mechanics_非保守力", "非保守力", "college",
     {"zh": "非保守力", "en": "Non-Conservative Force", "de": "Nichtkonservative Kraft"}),
    ("mechanics_质点系", "质点系", "college",
     {"zh": "质点系", "en": "System of Particles", "de": "Teilchensystem"}),
    ("mechanics_质心运动定理", "质心运动定理", "college",
     {"zh": "质心运动定理", "en": "Center of Mass Theorem", "de": "Satz vom Schwerpunkt"}),
    ("mechanics_变质量系统", "变质量系统", "college",
     {"zh": "变质量系统", "en": "Variable Mass System", "de": "System veränderlicher Masse"}),
    ("mechanics_两体问题", "两体问题", "college",
     {"zh": "两体问题", "en": "Two-Body Problem", "de": "Zweikörperproblem"}),
]

# ──────────────────────────────────────────────────────
# SECTION 2: THERMODYNAMICS
# ──────────────────────────────────────────────────────

thermo_mid = [
    ("thermo_温度", "温度", "middle",
     {"zh": "温度", "en": "Temperature", "de": "Temperatur"}),
    ("thermo_摄氏温度", "摄氏温度", "middle",
     {"zh": "摄氏温度", "en": "Celsius Temperature", "de": "Celsius-Temperatur"}),
    ("thermo_热力学温度", "热力学温度", "middle",
     {"zh": "热力学温度", "en": "Thermodynamic Temperature", "de": "Thermodynamische Temperatur"}),
    ("thermo_内能", "内能", "middle",
     {"zh": "内能", "en": "Internal Energy", "de": "Innere Energie"}),
    ("thermo_热量", "热量", "middle",
     {"zh": "热量", "en": "Heat", "de": "Wärme"}),
    ("thermo_比热容", "比热容", "middle",
     {"zh": "比热容", "en": "Specific Heat Capacity", "de": "Wärmekapazität"}),
    ("thermo_热传递", "热传递", "middle",
     {"zh": "热传递", "en": "Heat Transfer", "de": "Wärmetransport"}),
    ("thermo_热传导", "热传导", "middle",
     {"zh": "热传导", "en": "Thermal Conduction", "de": "Wärmeleitung"}),
    ("thermo_热对流", "热对流", "middle",
     {"zh": "热对流", "en": "Convection", "de": "Konvektion"}),
    ("thermo_热辐射", "热辐射", "middle",
     {"zh": "热辐射", "en": "Thermal Radiation", "de": "Wärmeabstrahlung"}),
    ("thermo_物态变化", "物态变化", "middle",
     {"zh": "物态变化", "en": "Phase Changes", "de": "Zustandsänderungen"}),
    ("thermo_熔化", "熔化", "middle",
     {"zh": "熔化", "en": "Melting", "de": "Schmelzen"}),
    ("thermo_凝固", "凝固", "middle",
     {"zh": "凝固", "en": "Solidification", "de": "Erstarren"}),
    ("thermo_汽化", "汽化", "middle",
     {"zh": "汽化", "en": "Vaporization", "de": "Verdampfung"}),
    ("thermo_液化", "液化", "middle",
     {"zh": "液化", "en": "Condensation", "de": "Kondensation"}),
    ("thermo_升华", "升华", "middle",
     {"zh": "升华", "en": "Sublimation", "de": "Sublimation"}),
    ("thermo_凝华", "凝华", "middle",
     {"zh": "凝华", "en": "Deposition", "de": "Deposition"}),
    ("thermo_熔点", "熔点", "middle",
     {"zh": "熔点", "en": "Melting Point", "de": "Schmelzpunkt"}),
    ("thermo_沸点", "沸点", "middle",
     {"zh": "沸点", "en": "Boiling Point", "de": "Siedepunkt"}),
    ("thermo_汽化热", "汽化热", "middle",
     {"zh": "汽化热", "en": "Latent Heat of Vaporization", "de": "Verdampfungswärme"}),
    ("thermo_分子动理论", "分子动理论", "middle",
     {"zh": "分子动理论", "en": "Kinetic Molecular Theory", "de": "Kinetische Gastheorie"}),
]

thermo_high = [
    ("thermo_气体实验定律", "气体实验定律", "high",
     {"zh": "气体实验定律", "en": "Gas Laws", "de": "Gasgesetze"}),
    ("thermo_玻意耳定律", "玻意耳定律", "high",
     {"zh": "玻意耳定律", "en": "Boyle's Law", "de": "Boyle-Mariotte-Gesetz"}),
    ("thermo_查理定律", "查理定律", "high",
     {"zh": "查理定律", "en": "Charles's Law", "de": "Gay-Lussac-Gesetz"}),
    ("thermo_盖-吕萨克定律", "盖-吕萨克定律", "high",
     {"zh": "盖-吕萨克定律", "en": "Gay-Lussac's Law", "de": "Gay-Lussac-Gesetz (Druck)"}),
    ("thermo_理想气体状态方程", "理想气体状态方程", "high",
     {"zh": "理想气体状态方程", "en": "Ideal Gas Law", "de": "Ideales Gasgesetz"}),
    ("thermo_阿伏伽德罗常数", "阿伏伽德罗常数", "high",
     {"zh": "阿伏伽德罗常数", "en": "Avogadro's Number", "de": "Avogadro-Konstante"}),
    ("thermo_分子平均动能", "分子平均动能", "high",
     {"zh": "分子平均动能", "en": "Average Molecular Kinetic Energy", "de": "Mittlere molekulare Kinetische Energie"}),
    ("thermo_布朗运动", "布朗运动", "high",
     {"zh": "布朗运动", "en": "Brownian Motion", "de": "Brownsche Bewegung"}),
    ("thermo_晶体", "晶体", "high",
     {"zh": "晶体", "en": "Crystal", "de": "Kristall"}),
    ("thermo_非晶体", "非晶体", "high",
     {"zh": "非晶体", "en": "Amorphous Solid", "de": "Amorpher Festkörper"}),
    ("thermo_液晶", "液晶", "high",
     {"zh": "液晶", "en": "Liquid Crystal", "de": "Flüssigkristall"}),
    ("thermo_饱和汽", "饱和汽", "high",
     {"zh": "饱和汽", "en": "Saturated Vapor", "de": "Gesättigter Dampf"}),
    ("thermo_空气湿度", "空气湿度", "high",
     {"zh": "空气湿度", "en": "Humidity", "de": "Luftfeuchtigkeit"}),
]

thermo_college = [
    ("thermo_热力学第一定律", "热力学第一定律", "college",
     {"zh": "热力学第一定律", "en": "First Law of Thermodynamics", "de": "1. Hauptsatz der Thermodynamik"}),
    ("thermo_热力学第二定律", "热力学第二定律", "college",
     {"zh": "热力学第二定律", "en": "Second Law of Thermodynamics", "de": "2. Hauptsatz der Thermodynamik"}),
    ("thermo_热力学第三定律", "热力学第三定律", "college",
     {"zh": "热力学第三定律", "en": "Third Law of Thermodynamics", "de": "3. Hauptsatz der Thermodynamik"}),
    ("thermo_熵", "熵", "college",
     {"zh": "熵", "en": "Entropy", "de": "Entropie"}),
    ("thermo_焓", "焓", "college",
     {"zh": "焓", "en": "Enthalpy", "de": "Enthalpie"}),
    ("thermo_自由能", "自由能", "college",
     {"zh": "自由能", "en": "Free Energy", "de": "Freie Energie"}),
    ("thermo_卡诺循环", "卡诺循环", "college",
     {"zh": "卡诺循环", "en": "Carnot Cycle", "de": "Carnot-Prozess"}),
    ("thermo_等温过程", "等温过程", "college",
     {"zh": "等温过程", "en": "Isothermal Process", "de": "Isothermer Prozess"}),
    ("thermo_等容过程", "等容过程", "college",
     {"zh": "等容过程", "en": "Isochoric Process", "de": "Ischoren Prozess"}),
    ("thermo_等压过程", "等压过程", "college",
     {"zh": "等压过程", "en": "Isobaric Process", "de": "Isobarer Prozess"}),
    ("thermo_绝热过程", "绝热过程", "college",
     {"zh": "绝热过程", "en": "Adiabatic Process", "de": "Adiabatischer Prozess"}),
    ("thermo_热机效率", "热机效率", "college",
     {"zh": "热机效率", "en": "Heat Engine Efficiency", "de": "Wirkungsgrad"}),
    ("thermo_制冷系数", "制冷系数", "college",
     {"zh": "制冷系数", "en": "Coefficient of Performance", "de": "Arbeitszahl"}),
    ("thermo_麦克斯韦速度分布", "麦克斯韦速度分布", "college",
     {"zh": "麦克斯韦速度分布", "en": "Maxwell-Boltzmann Distribution", "de": "Maxwell-Verteilung"}),
    ("thermo_能量均分定理", "能量均分定理", "college",
     {"zh": "能量均分定理", "en": "Equipartition Theorem", "de": "Gleichverteilungssatz"}),
    ("thermo_实际气体", "实际气体", "college",
     {"zh": "实际气体", "en": "Real Gases", "de": "Reale Gase"}),
    ("thermo_范德瓦尔斯方程", "范德瓦尔斯方程", "college",
     {"zh": "范德瓦尔斯方程", "en": "Van der Waals Equation", "de": "Van-der-Waals-Gleichung"}),
]

# ──────────────────────────────────────────────────────
# SECTION 3: ELECTROMAGNETISM
# ──────────────────────────────────────────────────────

em_mid = [
    ("em_电荷", "电荷", "middle",
     {"zh": "电荷", "en": "Electric Charge", "de": "Elektrische Ladung"}),
    ("em_正电荷", "正电荷", "middle",
     {"zh": "正电荷", "en": "Positive Charge", "de": "Positive Ladung"}),
    ("em_负电荷", "负电荷", "middle",
     {"zh": "负电荷", "en": "Negative Charge", "de": "Negative Ladung"}),
    ("em_电荷守恒", "电荷守恒定律", "middle",
     {"zh": "电荷守恒定律", "en": "Conservation of Charge", "de": "Ladungserhaltung"}),
    ("em_导体", "导体", "middle",
     {"zh": "导体", "en": "Conductor", "de": "Leiter"}),
    ("em_绝缘体", "绝缘体", "middle",
     {"zh": "绝缘体", "en": "Insulator", "de": "Isolator"}),
    ("em_半导体", "半导体", "middle",
     {"zh": "半导体", "en": "Semiconductor", "de": "Halbleiter"}),
    ("em_电路", "电路", "middle",
     {"zh": "电路", "en": "Electric Circuit", "de": "Elektrischer Stromkreis"}),
    ("em_电流", "电流", "middle",
     {"zh": "电流", "en": "Electric Current", "de": "Elektrischer Strom"}),
    ("em_电压", "电压", "middle",
     {"zh": "电压", "en": "Voltage", "de": "Spannung"}),
    ("em_电阻", "电阻", "middle",
     {"zh": "电阻", "en": "Resistance", "de": "Widerstand"}),
    ("em_欧姆定律", "欧姆定律", "middle",
     {"zh": "欧姆定律", "en": "Ohm's Law", "de": "Ohmsches Gesetz"}),
    ("em_串联", "串联电路", "middle",
     {"zh": "串联电路", "en": "Series Circuit", "de": "Reihenschaltung"}),
    ("em_并联", "并联电路", "middle",
     {"zh": "并联电路", "en": "Parallel Circuit", "de": "Parallelschaltung"}),
    ("em_电功率", "电功率", "middle",
     {"zh": "电功率", "en": "Electric Power", "de": "Elektrische Leistung"}),
    ("em_焦耳定律", "焦耳定律", "middle",
     {"zh": "焦耳定律", "en": "Joule's Law", "de": "Joulesche Wärme"}),
    ("em_电能", "电能", "middle",
     {"zh": "电能", "en": "Electrical Energy", "de": "Elektrische Energie"}),
    ("em_家庭电路", "家庭电路", "middle",
     {"zh": "家庭电路", "en": "Household Circuits", "de": "Haushaltsschaltung"}),
    ("em_安全用电", "安全用电", "middle",
     {"zh": "安全用电", "en": "Electrical Safety", "de": "Elektrische Sicherheit"}),
    ("em_电场线", "电场线", "middle",
     {"zh": "电场线", "en": "Electric Field Lines", "de": "Äquipotentiallinien"}),
    ("em_磁场", "磁场", "middle",
     {"zh": "磁场", "en": "Magnetic Field", "de": "Magnetisches Feld"}),
    ("em_磁感线", "磁感线", "middle",
     {"zh": "磁感线", "en": "Magnetic Field Lines", "de": "Magnetfeldlinien"}),
    ("em_电磁铁", "电磁铁", "middle",
     {"zh": "电磁铁", "en": "Electromagnet", "de": "Elektromagnet"}),
    ("em_电磁感应", "电磁感应", "middle",
     {"zh": "电磁感应", "en": "Electromagnetic Induction", "de": "Elektromagnetische Induktion"}),
    ("em_发电机", "发电机", "middle",
     {"zh": "发电机", "en": "Generator", "de": "Generator"}),
    ("em_电动机", "电动机", "middle",
     {"zh": "电动机", "en": "Electric Motor", "de": "Elektromotor"}),
    ("em_变压器", "变压器", "middle",
     {"zh": "变压器", "en": "Transformer", "de": "Transformator"}),
    ("em_交流电", "交流电", "middle",
     {"zh": "交流电", "en": "Alternating Current", "de": "Wechselstrom"}),
    ("em_直流电", "直流电", "middle",
     {"zh": "直流电", "en": "Direct Current", "de": "Gleichstrom"}),
    ("em_超导现象", "超导现象", "middle",
     {"zh": "超导现象", "en": "Superconductivity", "de": "Supraleitung"}),
]

em_high = [
    ("em_库仑定律", "库仑定律", "high",
     {"zh": "库仑定律", "en": "Coulomb's Law", "de": "Coulomb-Gesetz"}),
    ("em_电场强度", "电场强度", "high",
     {"zh": "电场强度", "en": "Electric Field Strength", "de": "Elektrische Feldstärke"}),
    ("em_点电荷电场", "点电荷的电场", "high",
     {"zh": "点电荷的电场", "en": "Point Charge Field", "de": "Feld einer Punktladung"}),
    ("em_电场叠加", "电场叠加原理", "high",
     {"zh": "电场叠加原理", "en": "Superposition of Electric Fields", "de": "Superpositionsprinzip (Elektrisches Feld)"}),
    ("em_电势", "电势", "high",
     {"zh": "电势", "en": "Electric Potential", "de": "Elektrisches Potential"}),
    ("em_电势差", "电势差", "high",
     {"zh": "电势差", "en": "Potential Difference", "de": "Potentialdifferenz"}),
    ("em_等势面", "等势面", "high",
     {"zh": "等势面", "en": "Equipotential Surface", "de": "Äquipotentialfläche"}),
    ("em_电势能", "电势能", "high",
     {"zh": "电势能", "en": "Electric Potential Energy", "de": "Elektrische potentielle Energie"}),
    ("em_电容", "电容", "high",
     {"zh": "电容", "en": "Capacitance", "de": "Kapazität"}),
    ("em_平行板电容器", "平行板电容器", "high",
     {"zh": "平行板电容器", "en": "Parallel Plate Capacitor", "de": "Plattenkondensator"}),
    ("em_电容器的充放电", "电容器的充放电", "high",
     {"zh": "电容器的充放电", "en": "Capacitor Charging/Discharging", "de": "Kondensatorladen/Entladen"}),
    ("em_电场力做功", "电场力做功", "high",
     {"zh": "电场力做功", "en": "Work by Electric Force", "de": "Arbeit der elektrischen Kraft"}),
    ("em_电阻定律", "电阻定律", "high",
     {"zh": "电阻定律", "en": "Resistance Law", "de": "Widerstandsgesetz"}),
    ("em_电阻率", "电阻率", "high",
     {"zh": "电阻率", "en": "Resistivity", "de": "Spezifischer Widerstand"}),
    ("em_基尔霍夫定律", "基尔霍夫定律", "high",
     {"zh": "基尔霍夫定律", "en": "Kirchhoff's Laws", "de": "Kirchhoffsche Gesetze"}),
    ("em_洛伦兹力", "洛伦兹力", "high",
     {"zh": "洛伦兹力", "en": "Lorentz Force", "de": "Lorentzkraft"}),
    ("em_安培力", "安培力", "high",
     {"zh": "安培力", "en": "Magnetic Force on Current", "de": "Magnetische Kraft auf Strom"}),
    ("em_磁通量", "磁通量", "high",
     {"zh": "磁通量", "en": "Magnetic Flux", "de": "Magnetische Flussdichte"}),
    ("em_法拉第电磁感应定律", "法拉第电磁感应定律", "high",
     {"zh": "法拉第电磁感应定律", "en": "Faraday's Law", "de": "Faradaysches Induktionsgesetz"}),
    ("em_楞次定律", "楞次定律", "high",
     {"zh": "楞次定律", "en": "Lenz's Law", "de": "Lenzsches Gesetz"}),
    ("em_自感", "自感", "high",
     {"zh": "自感", "en": "Self-Inductance", "de": "Selbstinduktion"}),
    ("em_互感", "互感", "high",
     {"zh": "互感", "en": "Mutual Inductance", "de": "Gegenseitige Induktion"}),
    ("em_电感", "电感", "high",
     {"zh": "电感", "en": "Inductance", "de": "Induktivität"}),
    ("em_交变电流的产生", "交变电流的产生", "high",
     {"zh": "交变电流的产生", "en": "Generation of AC", "de": "Erzeugung von Wechselstrom"}),
    ("em_交变电流的描述", "交变电流的描述", "high",
     {"zh": "交变电流的描述", "en": "Description of AC", "de": "Beschreibung von Wechselstrom"}),
    ("em_有效值", "交变电流的有效值", "high",
     {"zh": "交变电流的有效值", "en": "RMS Value of AC", "de": "Effektivwert von Wechselstrom"}),
    ("em_变压器原理", "变压器原理", "high",
     {"zh": "变压器原理", "en": "Transformer Principle", "de": "Transformatorprinzip"}),
    ("em_远距离输电", "远距离输电", "high",
     {"zh": "远距离输电", "en": "Long-Distance Power Transmission", "de": "Fernübertragung"}),
    ("em_霍尔效应", "霍尔效应", "high",
     {"zh": "霍尔效应", "en": "Hall Effect", "de": "Halleffekt"}),
    ("em_涡流", "涡流", "high",
     {"zh": "涡流", "en": "Eddy Currents", "de": "Wirbelströme"}),
]

em_college = [
    ("em_高斯定理", "高斯定理", "college",
     {"zh": "高斯定理", "en": "Gauss's Law", "de": "Gaußsches Gesetz"}),
    ("em_安培环路定理", "安培环路定理", "college",
     {"zh": "安培环路定理", "en": "Ampère's Circuital Law", "de": "Amperesches Gesetz"}),
    ("em_电位移", "电位移", "college",
     {"zh": "电位移", "en": "Electric Displacement", "de": "Verschiebungsstromdichte"}),
    ("em_电介质", "电介质", "college",
     {"zh": "电介质", "en": "Dielectric", "de": "Dielektrikum"}),
    ("em_电介质极化", "电介质极化", "college",
     {"zh": "电介质极化", "en": "Dielectric Polarization", "de": "Dielektrische Polarisation"}),
    ("em_电场能量", "电场能量", "college",
     {"zh": "电场能量", "en": "Electric Field Energy", "de": "Energie des elektrischen Feldes"}),
    ("em_磁场能量", "磁场能量", "college",
     {"zh": "磁场能量", "en": "Magnetic Field Energy", "de": "Energie des magnetischen Feldes"}),
    ("em_位移电流", "位移电流", "college",
     {"zh": "位移电流", "en": "Displacement Current", "de": "Verschiebungsstrom"}),
    ("em_麦克斯韦方程组", "麦克斯韦方程组", "college",
     {"zh": "麦克斯韦方程组", "en": "Maxwell's Equations", "de": "Maxwellsche Gleichungen"}),
    ("em_电磁波", "电磁波", "college",
     {"zh": "电磁波", "en": "Electromagnetic Waves", "de": "Elektromagnetische Wellen"}),
    ("em_电磁波谱", "电磁波谱", "college",
     {"zh": "电磁波谱", "en": "Electromagnetic Spectrum", "de": "Elektromagnetisches Spektrum"}),
    ("em_坡印廷矢量", "坡印廷矢量", "college",
     {"zh": "坡印廷矢量", "en": "Poynting Vector", "de": "Poynting-Vektor"}),
    ("em_电磁场的边界条件", "电磁场的边界条件", "college",
     {"zh": "电磁场的边界条件", "en": "Boundary Conditions of EM Fields", "de": "Randbedingungen des EM Feldes"}),
    ("em_磁介质", "磁介质", "college",
     {"zh": "磁介质", "en": "Magnetic Medium", "de": "Magnetisches Medium"}),
    ("em_磁化强度", "磁化强度", "college",
     {"zh": "磁化强度", "en": "Magnetization", "de": "Magnetisierung"}),
    ("em_铁磁性", "铁磁性", "college",
     {"zh": "铁磁性", "en": "Ferromagnetism", "de": "Ferromagnetismus"}),
    ("em_磁滞回线", "磁滞回线", "college",
     {"zh": "磁滞回线", "en": "Hysteresis Loop", "de": "Hysterese-Schleife"}),
    ("em_超导体", "超导体", "college",
     {"zh": "超导体", "en": "Superconductor", "de": "Supraleiter"}),
    ("em_迈斯纳效应", "迈斯纳效应", "college",
     {"zh": "迈斯纳效应", "en": "Meissner Effect", "de": "Meissner-Effekt"}),
    ("em_电磁感应定律的微分形式", "法拉第定律微分形式", "college",
     {"zh": "法拉第定律微分形式", "en": "Differential Form of Faraday's Law", "de": "Differentialform des Faradayschen Gesetzes"}),
]

# ──────────────────────────────────────────────────────
# SECTION 4: OPTICS
# ──────────────────────────────────────────────────────

optics_mid = [
    ("optics_光的直线传播", "光的直线传播", "middle",
     {"zh": "光的直线传播", "en": "Rectilinear Propagation of Light", "de": "Geradlinige Ausbreitung des Lichts"}),
    ("optics_光的反射", "光的反射", "middle",
     {"zh": "光的反射", "en": "Reflection of Light", "de": "Reflexion des Lichts"}),
    ("optics_平面镜成像", "平面镜成像", "middle",
     {"zh": "平面镜成像", "en": "Plane Mirror Imaging", "de": "Spiegelbild"}),
    ("optics_光的折射", "光的折射", "middle",
     {"zh": "光的折射", "en": "Refraction of Light", "de": "Lichtbrechung"}),
    ("optics_折射定律", "折射定律", "middle",
     {"zh": "折射定律", "en": "Snell's Law", "de": "Brechungsgesetz"}),
    ("optics_色散", "色散", "middle",
     {"zh": "色散", "en": "Dispersion", "de": "Dispersion"}),
    ("optics_凸透镜", "凸透镜", "middle",
     {"zh": "凸透镜", "en": "Convex Lens", "de": "Konvexlinse"}),
    ("optics_凹透镜", "凹透镜", "middle",
     {"zh": "凹透镜", "en": "Concave Lens", "de": "Konkavlinse"}),
    ("optics_透镜成像规律", "透镜成像规律", "middle",
     {"zh": "透镜成像规律", "en": "Lens Imaging Rules", "de": "Linsenabbildungsgesetze"}),
    ("optics_光的色散", "光的色散", "middle",
     {"zh": "光的色散", "en": "Dispersion of Light", "de": "Lichtdispersion"}),
    ("optics_光谱", "光谱", "middle",
     {"zh": "光谱", "en": "Spectrum", "de": "Spektrum"}),
    ("optics_红外线", "红外线", "middle",
     {"zh": "红外线", "en": "Infrared", "de": "Infrarot"}),
    ("optics_紫外线", "紫外线", "middle",
     {"zh": "紫外线", "en": "Ultraviolet", "de": "Ultraviolett"}),
    ("optics_光的能量", "光的能量", "middle",
     {"zh": "光的能量", "en": "Energy of Light", "de": "Lichtenergie"}),
]

optics_high = [
    ("optics_全反射", "全反射", "high",
     {"zh": "全反射", "en": "Total Internal Reflection", "de": "Totale Reflexion"}),
    ("optics_临界角", "临界角", "high",
     {"zh": "临界角", "en": "Critical Angle", "de": "Kritischer Winkel"}),
    ("optics_光纤", "光纤", "high",
     {"zh": "光纤", "en": "Optical Fiber", "de": "Glasfaser"}),
    ("optics_光导纤维", "光导纤维", "high",
     {"zh": "光导纤维", "en": "Light Guide Fiber", "de": "Lichtleitfaser"}),
    ("optics_光的干涉", "光的干涉", "high",
     {"zh": "光的干涉", "en": "Light Interference", "de": "Lichtinterferenz"}),
    ("optics_双缝干涉", "双缝干涉", "high",
     {"zh": "双缝干涉", "en": "Double-Slit Interference", "de": "Doppelspaltinterferenz"}),
    ("optics_薄膜干涉", "薄膜干涉", "high",
     {"zh": "薄膜干涉", "en": "Thin Film Interference", "de": "Dünnschichtinterferenz"}),
    ("optics_光的衍射", "光的衍射", "high",
     {"zh": "光的衍射", "en": "Light Diffraction", "de": "Beugung des Lichts"}),
    ("optics_单缝衍射", "单缝衍射", "high",
     {"zh": "单缝衍射", "en": "Single-Slit Diffraction", "de": "Einzelspaltbeugung"}),
    ("optics_光栅", "光栅", "high",
     {"zh": "光栅", "en": "Diffraction Grating", "de": "Beugungsgitter"}),
    ("optics_偏振", "偏振", "high",
     {"zh": "偏振", "en": "Polarization", "de": "Polarisation"}),
    ("optics_自然光", "自然光", "high",
     {"zh": "自然光", "en": "Natural Light", "de": "Natürliches Licht"}),
    ("optics_偏振光", "偏振光", "high",
     {"zh": "偏振光", "en": "Polarized Light", "de": "Polarisiertes Licht"}),
    ("optics_马吕斯定律", "马吕斯定律", "high",
     {"zh": "马吕斯定律", "en": "Malus's Law", "de": "Malussches Gesetz"}),
    ("optics_布儒斯特定律", "布儒斯特定律", "high",
     {"zh": "布儒斯特定律", "en": "Brewster's Law", "de": "Brewstersches Gesetz"}),
    ("optics_光的偏振应用", "光的偏振应用", "high",
     {"zh": "光的偏振应用", "en": "Applications of Polarization", "de": "Anwendungen der Polarisation"}),
]

optics_college = [
    ("optics_光的相干性", "光的相干性", "college",
     {"zh": "光的相干性", "en": "Coherence of Light", "de": "Kohärenz des Lichts"}),
    ("optics_相干长度", "相干长度", "college",
     {"zh": "相干长度", "en": "Coherence Length", "de": "Kohärenzlänge"}),
    ("optics_多光束干涉", "多光束干涉", "college",
     {"zh": "多光束干涉", "en": "Multi-Beam Interference", "de": "Mehrstrahlinterferenz"}),
    ("optics_法布里-珀罗干涉仪", "法布里-珀罗干涉仪", "college",
     {"zh": "法布里-珀罗干涉仪", "en": "Fabry-Perot Interferometer", "de": "Fabry-Perot-Interferometer"}),
    ("optics_光的偏振态", "光的偏振态", "college",
     {"zh": "光的偏振态", "en": "Polarization State of Light", "de": "Polarisationszustand des Lichts"}),
    ("optics_椭圆偏振", "椭圆偏振", "college",
     {"zh": "椭圆偏振", "en": "Elliptical Polarization", "de": "Elliptische Polarisation"}),
    ("optics_圆偏振", "圆偏振", "college",
     {"zh": "圆偏振", "en": "Circular Polarization", "de": "Zirkulare Polarisation"}),
    ("optics_波片", "波片", "college",
     {"zh": "波片", "en": "Wave Plate", "de": "Wellenplatte"}),
    ("optics_半波片", "半波片", "college",
     {"zh": "半波片", "en": "Half-Wave Plate", "de": "Halbwellenplatte"}),
    ("optics_四分之一波片", "四分之一波片", "college",
     {"zh": "四分之一波片", "en": "Quarter-Wave Plate", "de": "Viertelwellenplatte"}),
    ("optics_双折射", "双折射", "college",
     {"zh": "双折射", "en": "Birefringence", "de": "Doppelbrechung"}),
    ("optics_旋光性", "旋光性", "college",
     {"zh": "旋光性", "en": "Optical Activity", "de": "Optische Aktivität"}),
    ("optics_吸收光谱", "吸收光谱", "college",
     {"zh": "吸收光谱", "en": "Absorption Spectrum", "de": "Absorptionsspektrum"}),
    ("optics_发射光谱", "发射光谱", "college",
     {"zh": "发射光谱", "en": "Emission Spectrum", "de": "Emissionsspektrum"}),
    ("optics_连续光谱", "连续光谱", "college",
     {"zh": "连续光谱", "en": "Continuous Spectrum", "de": "Kontinuierliches Spektrum"}),
    ("optics_线状光谱", "线状光谱", "college",
     {"zh": "线状光谱", "en": "Line Spectrum", "de": "Linienspektrum"}),
    ("optics_带状光谱", "带状光谱", "college",
     {"zh": "带状光谱", "en": "Band Spectrum", "de": "Bandspektrum"}),
]

# ──────────────────────────────────────────────────────
# SECTION 5: MODERN PHYSICS
# ──────────────────────────────────────────────────────

modern_high = [
    ("modern_光电效应", "光电效应", "high",
     {"zh": "光电效应", "en": "Photoelectric Effect", "de": "Photoeffekt"}),
    ("modern_光子", "光子", "high",
     {"zh": "光子", "en": "Photon", "de": "Photon"}),
    ("modern_光子能量", "光子能量", "high",
     {"zh": "光子能量", "en": "Photon Energy", "de": "Photonenenergie"}),
    ("modern_逸出功", "逸出功", "high",
     {"zh": "逸出功", "en": "Work Function", "de": "Austrittsarbeit"}),
    ("modern_截止频率", "截止频率", "high",
     {"zh": "截止频率", "en": "Threshold Frequency", "de": "Grenzfrequenz"}),
    ("modern_康普顿效应", "康普顿效应", "high",
     {"zh": "康普顿效应", "en": "Compton Effect", "de": "Compton-Effekt"}),
    ("modern_波粒二象性", "波粒二象性", "high",
     {"zh": "波粒二象性", "en": "Wave-Particle Duality", "de": "Wellen-Teilchen-Dualismus"}),
    ("modern_德布罗意波", "德布罗意波", "high",
     {"zh": "德布罗意波", "en": "de Broglie Wave", "de": "de-Broglie-Wellenlänge"}),
    ("modern_原子核式结构", "原子核式结构", "high",
     {"zh": "原子核式结构", "en": "Nuclear Model of Atom", "de": "Kernmodell des Atoms"}),
    ("modern_玻尔模型", "玻尔模型", "high",
     {"zh": "玻尔模型", "en": "Bohr Model", "de": "Bohrsches Atommodell"}),
    ("modern_能级跃迁", "能级跃迁", "high",
     {"zh": "能级跃迁", "en": "Energy Level Transition", "de": "Energieniveauübergang"}),
    ("modern_光谱分析", "光谱分析", "high",
     {"zh": "光谱分析", "en": "Spectral Analysis", "de": "Spektralanalyse"}),
    ("modern_氢原子光谱", "氢原子光谱", "high",
     {"zh": "氢原子光谱", "en": "Hydrogen Spectrum", "de": "Wasserstoffspektrum"}),
    ("modern_放射性", "放射性", "high",
     {"zh": "放射性", "en": "Radioactivity", "de": "Radioaktivität"}),
    ("modern_α衰变", "α衰变", "high",
     {"zh": "α衰变", "en": "Alpha Decay", "de": "Alpha-Zerfall"}),
    ("modern_β衰变", "β衰变", "high",
     {"zh": "β衰变", "en": "Beta Decay", "de": "Beta-Zerfall"}),
    ("modern_γ射线", "γ射线", "high",
     {"zh": "γ射线", "en": "Gamma Rays", "de": "Gammastrahlung"}),
    ("modern_半衰期", "半衰期", "high",
     {"zh": "半衰期", "en": "Half-Life", "de": "Halbwertszeit"}),
    ("modern_原子核的组成", "原子核的组成", "high",
     {"zh": "原子核的组成", "en": "Nuclear Composition", "de": "Kernzusammensetzung"}),
    ("modern_核力", "核力", "high",
     {"zh": "核力", "en": "Nuclear Force", "de": "Kernkraft"}),
    ("modern_质量数", "质量数", "high",
     {"zh": "质量数", "en": "Mass Number", "de": "Massenzahl"}),
    ("modern_电荷数", "电荷数", "high",
     {"zh": "电荷数", "en": "Atomic Number", "de": "Ordnungszahl"}),
    ("modern_同位素", "同位素", "high",
     {"zh": "同位素", "en": "Isotope", "de": "Isotop"}),
    ("modern_核裂变", "核裂变", "high",
     {"zh": "核裂变", "en": "Nuclear Fission", "de": "Kernspaltung"}),
    ("modern_核聚变", "核聚变", "high",
     {"zh": "核聚变", "en": "Nuclear Fusion", "de": "Kernfusion"}),
    ("modern_链式反应", "链式反应", "high",
     {"zh": "链式反应", "en": "Chain Reaction", "de": "Kettenreaktion"}),
    ("modern_核反应堆", "核反应堆", "high",
     {"zh": "核反应堆", "en": "Nuclear Reactor", "de": "Kernreaktor"}),
    ("modern_原子弹", "原子弹", "high",
     {"zh": "原子弹", "en": "Atomic Bomb", "de": "Atombombe"}),
    ("modern_氢弹", "氢弹", "high",
     {"zh": "氢弹", "en": "Hydrogen Bomb", "de": "Wasserstoffbombe"}),
    ("modern_质能方程", "质能方程", "high",
     {"zh": "质能方程", "en": "Mass-Energy Equivalence", "de": "Massen-Energie-Äquivalenz"}),
]

modern_college = [
    ("modern_狭义相对论", "狭义相对论", "college",
     {"zh": "狭义相对论", "en": "Special Relativity", "de": "Spezielle Relativitätstheorie"}),
    ("modern_洛伦兹变换", "洛伦兹变换", "college",
     {"zh": "洛伦兹变换", "en": "Lorentz Transformation", "de": "Lorentz-Transformation"}),
    ("modern_时间膨胀", "时间膨胀", "college",
     {"zh": "时间膨胀", "en": "Time Dilation", "de": "Zeitdilatation"}),
    ("modern_长度收缩", "长度收缩", "college",
     {"zh": "长度收缩", "en": "Length Contraction", "de": "Längenkontraktion"}),
    ("modern_同时性的相对性", "同时性的相对性", "college",
     {"zh": "同时性的相对性", "en": "Relativity of Simultaneity", "de": "Relativität der Gleichzeitigkeit"}),
    ("modern_质速关系", "质速关系", "college",
     {"zh": "质速关系", "en": "Relativistic Mass", "de": "Relativistische Masse"}),
    ("modern_四维动量", "四维动量", "college",
     {"zh": "四维动量", "en": "Four-Momentum", "de": "Vierer-Impuls"}),
    ("modern_不确定性原理", "不确定性原理", "college",
     {"zh": "不确定性原理", "en": "Uncertainty Principle", "de": "Unschärferelation"}),
    ("modern_波函数", "波函数", "college",
     {"zh": "波函数", "en": "Wave Function", "de": "Wellenfunktion"}),
    ("modern_薛定谔方程", "薛定谔方程", "college",
     {"zh": "薛定谔方程", "en": "Schrödinger Equation", "de": "Schrödinger-Gleichung"}),
    ("modern_量子态", "量子态", "college",
     {"zh": "量子态", "en": "Quantum State", "de": "Quantenzustand"}),
    ("modern_量子叠加", "量子叠加", "college",
     {"zh": "量子叠加", "en": "Quantum Superposition", "de": "Quantenüberlagerung"}),
    ("modern_量子隧穿", "量子隧穿", "college",
     {"zh": "量子隧穿", "en": "Quantum Tunneling", "de": "Quantentunneln"}),
    ("modern_泡利不相容原理", "泡利不相容原理", "college",
     {"zh": "泡利不相容原理", "en": "Pauli Exclusion Principle", "de": "Pauli-Verbotsprinzip"}),
    ("modern_费米子", "费米子", "college",
     {"zh": "费米子", "en": "Fermion", "de": "Fermion"}),
    ("modern_玻色子", "玻色子", "college",
     {"zh": "玻色子", "en": "Boson", "de": "Boson"}),
    ("modern_光子统计", "光子统计", "college",
     {"zh": "光子统计", "en": "Photon Statistics", "de": "Photonenstatistik"}),
    ("modern_激光", "激光", "college",
     {"zh": "激光", "en": "Laser", "de": "Laser"}),
    ("modern_受激辐射", "受激辐射", "college",
     {"zh": "受激辐射", "en": "Stimulated Emission", "de": "Angeregte Emission"}),
    ("modern_自发辐射", "自发辐射", "college",
     {"zh": "自发辐射", "en": "Spontaneous Emission", "de": "Spontane Emission"}),
    ("modern_粒子物理标准模型", "粒子物理标准模型", "college",
     {"zh": "粒子物理标准模型", "en": "Standard Model of Particle Physics", "de": "Standardmodell der Teilchenphysik"}),
    ("modern_希格斯机制", "希格斯机制", "college",
     {"zh": "希格斯机制", "en": "Higgs Mechanism", "de": "Higgs-Mechanismus"}),
    ("modern_广义相对论简介", "广义相对论简介", "college",
     {"zh": "广义相对论简介", "en": "Introduction to General Relativity", "de": "Einführung in die Allgemeine Relativitätstheorie"}),
    ("modern_引力波", "引力波", "college",
     {"zh": "引力波", "en": "Gravitational Waves", "de": "Gravitationswellen"}),
]

# ──────────────────────────────────────────────────────
# SECTION 6: FLUID MECHANICS (college)
# ──────────────────────────────────────────────────────

fluid_college = [
    ("fluid_流体静力学", "流体静力学", "college",
     {"zh": "流体静力学", "en": "Fluid Statics", "de": "Hydrostatik"}),
    ("fluid_帕斯卡定律", "帕斯卡定律", "college",
     {"zh": "帕斯卡定律", "en": "Pascal's Law", "de": "Pascalsches Gesetz"}),
    ("fluid_伯努利方程", "伯努利方程", "college",
     {"zh": "伯努利方程", "en": "Bernoulli's Equation", "de": "Bernoulli-Gleichung"}),
    ("fluid_粘性", "粘性", "college",
     {"zh": "粘性", "en": "Viscosity", "de": "Viskosität"}),
    ("fluid_层流", "层流", "college",
     {"zh": "层流", "en": "Laminar Flow", "de": "Laminare Strömung"}),
    ("fluid_湍流", "湍流", "college",
     {"zh": "湍流", "en": "Turbulent Flow", "de": "Turbulente Strömung"}),
    ("fluid_雷诺数", "雷诺数", "college",
     {"zh": "雷诺数", "en": "Reynolds Number", "de": "Reynolds-Zahl"}),
    ("fluid_泊肃叶定律", "泊肃叶定律", "college",
     {"zh": "泊肃叶定律", "en": "Poiseuille's Law", "de": "Poiseuille-Gesetz"}),
    ("fluid_斯托克斯定律", "斯托克斯定律", "college",
     {"zh": "斯托克斯定律", "en": "Stokes' Law", "de": "Stokessches Gesetz"}),
    ("fluid_表面张力", "表面张力", "college",
     {"zh": "表面张力", "en": "Surface Tension", "de": "Oberflächenspannung"}),
    ("fluid_毛细现象", "毛细现象", "college",
     {"zh": "毛细现象", "en": "Capillary Action", "de": "Kapillarwirkung"}),
    ("fluid_连续性方程", "连续性方程", "college",
     {"zh": "连续性方程", "en": "Continuity Equation", "de": "Kontinuitätsgleichung"}),
]

# ──────────────────────────────────────────────────────
# SECTION 7: NUCLEAR & PARTICLE (college)
# ──────────────────────────────────────────────────────

nuclear_college = [
    ("nuclear_放射性衰变规律", "放射性衰变规律", "college",
     {"zh": "放射性衰变规律", "en": "Radioactive Decay Law", "de": "Zerfallsgesetz"}),
    ("nuclear_衰变常数", "衰变常数", "college",
     {"zh": "衰变常数", "en": "Decay Constant", "de": "Zerfallskonstante"}),
    ("nuclear_比活度", "比活度", "college",
     {"zh": "比活度", "en": "Specific Activity", "de": "Spezifische Aktivität"}),
    ("nuclear_核反应截面", "核反应截面", "college",
     {"zh": "核反应截面", "en": "Nuclear Cross Section", "de": "Kernwirkungsquerschnitt"}),
    ("nuclear_中子", "中子", "college",
     {"zh": "中子", "en": "Neutron", "de": "Neutron"}),
    ("nuclear_质子", "质子", "college",
     {"zh": "质子", "en": "Proton", "de": "Proton"}),
    ("nuclear_电子", "电子", "college",
     {"zh": "电子", "en": "Electron", "de": "Elektron"}),
    ("nuclear_正电子", "正电子", "college",
     {"zh": "正电子", "en": "Positron", "de": "Positron"}),
    ("nuclear_中微子", "中微子", "college",
     {"zh": "中微子", "en": "Neutrino", "de": "Neutrino"}),
    ("nuclear_夸克", "夸克", "college",
     {"zh": "夸克", "en": "Quark", "de": "Quark"}),
    ("nuclear_轻子", "轻子", "college",
     {"zh": "轻子", "en": "Lepton", "de": "Lepton"}),
    ("nuclear_介子", "介子", "college",
     {"zh": "介子", "en": "Meson", "de": "Meson"}),
    ("nuclear_强相互作用", "强相互作用", "college",
     {"zh": "强相互作用", "en": "Strong Interaction", "de": "Starke Wechselwirkung"}),
    ("nuclear_弱相互作用", "弱相互作用", "college",
     {"zh": "弱相互作用", "en": "Weak Interaction", "de": "Schwache Wechselwirkung"}),
    ("nuclear_电磁相互作用", "电磁相互作用", "college",
     {"zh": "电磁相互作用", "en": "Electromagnetic Interaction", "de": "Elektromagnetische Wechselwirkung"}),
    ("nuclear_引力相互作用", "引力相互作用", "college",
     {"zh": "引力相互作用", "en": "Gravitational Interaction", "de": "Gravitationswechselwirkung"}),
]

# ── Combine all concept groups ──────────────────────────

all_groups = []
all_groups.extend(mechanics_basics)
all_groups.extend(mechanics_forces_mid)
all_groups.extend(mechanics_high)
all_groups.extend(mechanics_college)
all_groups.extend(thermo_mid)
all_groups.extend(thermo_high)
all_groups.extend(thermo_college)
all_groups.extend(em_mid)
all_groups.extend(em_high)
all_groups.extend(em_college)
all_groups.extend(optics_mid)
all_groups.extend(optics_high)
all_groups.extend(optics_college)
all_groups.extend(modern_high)
all_groups.extend(modern_college)
all_groups.extend(fluid_college)
all_groups.extend(nuclear_college)

# Debug: check for non-4-element entries
for i, g in enumerate(all_groups):
    if len(g) != 4:
        print(f"Entry {i} has {len(g)} elements: {g[:2]}...")


def build_concept(group):
    if isinstance(group, list):
        # Unwrap if accidentally nested
        if len(group) == 1:
            group = group[0]
        elif len(group) > 4:
            # This is a nested list — skip it
            return None
    name, display, level, labels = group
    # Generate source references from publisher catalogs
    refs = []
    for lang, pubs in [("zh", ZH_PUBLISHERS), ("en", EN_PUBLISHERS), ("de", DE_PUBLISHERS)]:
        level_pubs = pubs.get(level, [])
        for pub_name, chap, sec in level_pubs[:2]:  # Max 2 per language
            refs.append(make_ref(lang, pub_name, chap, sec))
    return concept(name, display, level, labels, refs)


# ══════════════════════════════════════════════════════════════════════
#  RELATIONS
# ══════════════════════════════════════════════════════════════════════

def rel(src, tgt, rtype):
    return {"source": f"physics_{src}", "target": f"physics_{tgt}", "type": rtype, "relation": rtype}


relations = [
    # ── Mechanics basics ──
    rel("mechanics_运动", "mechanics_参照系", "requires"),
    rel("mechanics_位移", "mechanics_运动", "part_of"),
    rel("mechanics_路程", "mechanics_运动", "part_of"),
    rel("mechanics_速度", "mechanics_位移", "requires"),
    rel("mechanics_速率", "mechanics_路程", "requires"),
    rel("mechanics_速度", "mechanics_速率", "analogy"),
    rel("mechanics_匀速直线运动", "mechanics_速度", "requires"),
    rel("mechanics_时间", "mechanics_运动", "requires"),
    rel("mechanics_长度测量", "mechanics_位移", "requires"),
    rel("mechanics_时间测量", "mechanics_时间", "requires"),

    # ── Middle school forces ──
    rel("mechanics_力", "mechanics_重力", "generalization"),
    rel("mechanics_力", "mechanics_弹力", "generalization"),
    rel("mechanics_力", "mechanics_摩擦力", "generalization"),
    rel("mechanics_质量", "mechanics_密度", "requires"),
    rel("mechanics_二力平衡", "mechanics_力", "requires"),
    rel("mechanics_惯性", "mechanics_质量", "requires"),
    rel("mechanics_简单机械", "mechanics_杠杆", "generalization"),
    rel("mechanics_简单机械", "mechanics_滑轮", "generalization"),
    rel("mechanics_功", "mechanics_力", "requires"),
    rel("mechanics_功率", "mechanics_功", "requires"),
    rel("mechanics_机械能", "mechanics_动能", "generalization"),
    rel("mechanics_机械能", "mechanics_势能", "generalization"),
    rel("mechanics_能量转化", "mechanics_机械能", "requires"),
    rel("mechanics_压强", "mechanics_力", "requires"),
    rel("mechanics_大气压强", "mechanics_压强", "generalization"),
    rel("mechanics_浮力", "mechanics_压强", "requires"),
    rel("mechanics_阿基米德原理", "mechanics_浮力", "representation"),
    rel("mechanics_流体压强", "mechanics_压强", "requires"),

    # ── High school mechanics ──
    rel("mechanics_加速度", "mechanics_速度", "requires"),
    rel("mechanics_匀变速直线运动", "mechanics_加速度", "requires"),
    rel("mechanics_自由落体", "mechanics_匀变速直线运动", "specialization"),
    rel("mechanics_竖直上抛", "mechanics_匀变速直线运动", "specialization"),
    rel("mechanics_平抛运动", "mechanics_匀变速直线运动", "specialization"),
    rel("mechanics_斜抛运动", "mechanics_平抛运动", "specialization"),
    rel("mechanics_运动的合成与分解", "mechanics_平抛运动", "applies_to"),
    rel("mechanics_牛顿第一定律", "mechanics_惯性", "analogy"),
    rel("mechanics_牛顿第二定律", "mechanics_牛顿第一定律", "prerequisite"),
    rel("mechanics_牛顿第二定律", "mechanics_力", "requires"),
    rel("mechanics_牛顿第二定律", "mechanics_加速度", "requires"),
    rel("mechanics_牛顿第三定律", "mechanics_牛顿第二定律", "prerequisite"),
    rel("mechanics_动量", "mechanics_质量", "requires"),
    rel("mechanics_动量", "mechanics_速度", "requires"),
    rel("mechanics_冲量", "mechanics_力", "requires"),
    rel("mechanics_动量守恒", "mechanics_动量", "requires"),
    rel("mechanics_碰撞", "mechanics_动量守恒", "applies_to"),
    rel("mechanics_弹性碰撞", "mechanics_碰撞", "specialization"),
    rel("mechanics_非弹性碰撞", "mechanics_碰撞", "specialization"),
    rel("mechanics_完全非弹性碰撞", "mechanics_非弹性碰撞", "specialization"),
    rel("mechanics_动能定理", "mechanics_功", "requires"),
    rel("mechanics_动能定理", "mechanics_动能", "requires"),
    rel("mechanics_机械能守恒", "mechanics_动能", "requires"),
    rel("mechanics_机械能守恒", "mechanics_势能", "requires"),
    rel("mechanics_能量守恒", "mechanics_机械能守恒", "generalization"),
    rel("mechanics_万有引力", "mechanics_重力", "generalization"),
    rel("mechanics_开普勒第一定律", "mechanics_万有引力", "representation"),
    rel("mechanics_开普勒第二定律", "mechanics_角动量", "applies_to"),
    rel("mechanics_开普勒第三定律", "mechanics_万有引力", "applies_to"),
    rel("mechanics_宇宙速度", "mechanics_万有引力", "requires"),
    rel("mechanics_卫星运动", "mechanics_万有引力", "requires"),
    rel("mechanics_圆周运动", "mechanics_牛顿第二定律", "requires"),
    rel("mechanics_向心加速度", "mechanics_圆周运动", "representation"),
    rel("mechanics_向心力", "mechanics_圆周运动", "representation"),
    rel("mechanics_离心现象", "mechanics_向心力", "analogy"),
    rel("mechanics_简谐运动", "mechanics_力", "requires"),
    rel("mechanics_单摆", "mechanics_简谐运动", "specialization"),
    rel("mechanics_弹簧振子", "mechanics_简谐运动", "specialization"),
    rel("mechanics_振动图像", "mechanics_简谐运动", "representation"),
    rel("mechanics_受迫振动", "mechanics_简谐运动", "requires"),
    rel("mechanics_共振", "mechanics_受迫振动", "specialization"),
    rel("mechanics_机械波", "mechanics_简谐运动", "prerequisite"),
    rel("mechanics_横波", "mechanics_机械波", "specialization"),
    rel("mechanics_纵波", "mechanics_机械波", "specialization"),
    rel("mechanics_波长", "mechanics_机械波", "part_of"),
    rel("mechanics_频率", "mechanics_机械波", "part_of"),
    rel("mechanics_波速", "mechanics_波长", "requires"),
    rel("mechanics_波速", "mechanics_频率", "requires"),
    rel("mechanics_波的叠加", "mechanics_机械波", "requires"),
    rel("mechanics_波的干涉", "mechanics_波的叠加", "applies_to"),
    rel("mechanics_波的衍射", "mechanics_机械波", "requires"),
    rel("mechanics_多普勒效应", "mechanics_波速", "applies_to"),
    rel("mechanics_驻波", "mechanics_波的叠加", "specialization"),
    rel("mechanics_声波", "mechanics_纵波", "specialization"),
    rel("mechanics_音调", "mechanics_声波", "representation"),
    rel("mechanics_响度", "mechanics_声波", "representation"),
    rel("mechanics_音色", "mechanics_声波", "representation"),
    rel("mechanics_回声", "mechanics_声波", "applies_to"),
    rel("mechanics_声速", "mechanics_声波", "representation"),

    # ── College mechanics ──
    rel("mechanics_力矩", "mechanics_力", "requires"),
    rel("mechanics_转动惯量", "mechanics_力矩", "requires"),
    rel("mechanics_角动量", "mechanics_力矩", "requires"),
    rel("mechanics_角动量", "mechanics_转动惯量", "requires"),
    rel("mechanics_角动量守恒", "mechanics_角动量", "requires"),
    rel("mechanics_转动动能", "mechanics_转动惯量", "requires"),
    rel("mechanics_刚体定轴转动", "mechanics_力矩", "requires"),
    rel("mechanics_刚体定轴转动", "mechanics_转动惯量", "requires"),
    rel("mechanics_刚体平面运动", "mechanics_刚体定轴转动", "generalization"),
    rel("mechanics_滚动摩擦", "mechanics_摩擦力", "specialization"),
    rel("mechanics_非惯性系", "mechanics_牛顿第一定律", "requires"),
    rel("mechanics_科里奥利力", "mechanics_非惯性系", "applies_to"),
    rel("mechanics_虚功原理", "mechanics_功", "requires"),
    rel("mechanics_拉格朗日方程", "mechanics_虚功原理", "prerequisite"),
    rel("mechanics_哈密顿方程", "mechanics_拉格朗日方程", "prerequisite"),
    rel("mechanics_弹性势能", "mechanics_势能", "specialization"),
    rel("mechanics_保守力", "mechanics_势能", "requires"),
    rel("mechanics_非保守力", "mechanics_保守力", "analogy"),
    rel("mechanics_质点系", "mechanics_牛顿第二定律", "generalization"),
    rel("mechanics_质心运动定理", "mechanics_质点系", "representation"),
    rel("mechanics_变质量系统", "mechanics_牛顿第二定律", "applies_to"),
    rel("mechanics_两体问题", "mechanics_万有引力", "applies_to"),

    # ── Thermodynamics ──
    rel("thermo_温度", "thermo_摄氏温度", "representation"),
    rel("thermo_温度", "thermo_热力学温度", "representation"),
    rel("thermo_内能", "thermo_温度", "requires"),
    rel("thermo_热量", "thermo_温度", "requires"),
    rel("thermo_比热容", "thermo_热量", "requires"),
    rel("thermo_热传递", "thermo_热量", "requires"),
    rel("thermo_热传导", "thermo_热传递", "specialization"),
    rel("thermo_热对流", "thermo_热传递", "specialization"),
    rel("thermo_热辐射", "thermo_热传递", "specialization"),
    rel("thermo_物态变化", "thermo_热量", "requires"),
    rel("thermo_熔化", "thermo_物态变化", "specialization"),
    rel("thermo_凝固", "thermo_熔化", "analogy"),
    rel("thermo_汽化", "thermo_物态变化", "specialization"),
    rel("thermo_液化", "thermo_汽化", "analogy"),
    rel("thermo_升华", "thermo_物态变化", "specialization"),
    rel("thermo_凝华", "thermo_升华", "analogy"),
    rel("thermo_熔点", "thermo_熔化", "representation"),
    rel("thermo_沸点", "thermo_汽化", "representation"),
    rel("thermo_汽化热", "thermo_汽化", "representation"),
    rel("thermo_分子动理论", "thermo_内能", "requires"),

    rel("thermo_气体实验定律", "thermo_分子动理论", "prerequisite"),
    rel("thermo_玻意耳定律", "thermo_气体实验定律", "specialization"),
    rel("thermo_查理定律", "thermo_气体实验定律", "specialization"),
    rel("thermo_盖-吕萨克定律", "thermo_气体实验定律", "specialization"),
    rel("thermo_理想气体状态方程", "thermo_玻意耳定律", "generalization"),
    rel("thermo_理想气体状态方程", "thermo_查理定律", "generalization"),
    rel("thermo_理想气体状态方程", "thermo_盖-吕萨克定律", "generalization"),
    rel("thermo_阿伏伽德罗常数", "thermo_理想气体状态方程", "requires"),
    rel("thermo_分子平均动能", "thermo_分子动理论", "representation"),
    rel("thermo_布朗运动", "thermo_分子动理论", "representation"),
    rel("thermo_晶体", "thermo_物态变化", "requires"),
    rel("thermo_非晶体", "thermo_晶体", "analogy"),
    rel("thermo_液晶", "thermo_晶体", "specialization"),
    rel("thermo_饱和汽", "thermo_汽化", "requires"),
    rel("thermo_空气湿度", "thermo_饱和汽", "applies_to"),

    rel("thermo_热力学第一定律", "thermo_内能", "requires"),
    rel("thermo_热力学第一定律", "thermo_热量", "requires"),
    rel("thermo_热力学第二定律", "thermo_热力学第一定律", "prerequisite"),
    rel("thermo_热力学第三定律", "thermo_热力学第二定律", "prerequisite"),
    rel("thermo_熵", "thermo_热力学第二定律", "representation"),
    rel("thermo_焓", "thermo_热力学第一定律", "representation"),
    rel("thermo_自由能", "thermo_熵", "requires"),
    rel("thermo_卡诺循环", "thermo_热力学第二定律", "applies_to"),
    rel("thermo_等温过程", "thermo_卡诺循环", "part_of"),
    rel("thermo_等容过程", "thermo_卡诺循环", "part_of"),
    rel("thermo_等压过程", "thermo_卡诺循环", "part_of"),
    rel("thermo_绝热过程", "thermo_卡诺循环", "part_of"),
    rel("thermo_热机效率", "thermo_卡诺循环", "representation"),
    rel("thermo_制冷系数", "thermo_卡诺循环", "representation"),
    rel("thermo_麦克斯韦速度分布", "thermo_分子动理论", "prerequisite"),
    rel("thermo_能量均分定理", "thermo_麦克斯韦速度分布", "prerequisite"),
    rel("thermo_实际气体", "thermo_理想气体状态方程", "generalization"),
    rel("thermo_范德瓦尔斯方程", "thermo_实际气体", "representation"),

    # ── Electromagnetism ──
    rel("em_电荷", "em_正电荷", "generalization"),
    rel("em_电荷", "em_负电荷", "generalization"),
    rel("em_电荷守恒", "em_电荷", "requires"),
    rel("em_导体", "em_电荷", "requires"),
    rel("em_绝缘体", "em_电荷", "requires"),
    rel("em_半导体", "em_导体", "specialization"),
    rel("em_电路", "em_电荷", "requires"),
    rel("em_电流", "em_电荷", "requires"),
    rel("em_电压", "em_电流", "requires"),
    rel("em_电阻", "em_电流", "requires"),
    rel("em_欧姆定律", "em_电压", "requires"),
    rel("em_欧姆定律", "em_电阻", "requires"),
    rel("em_串联", "em_电阻", "requires"),
    rel("em_并联", "em_电阻", "requires"),
    rel("em_电功率", "em_电压", "requires"),
    rel("em_电功率", "em_电流", "requires"),
    rel("em_焦耳定律", "em_电流", "requires"),
    rel("em_焦耳定律", "em_电阻", "requires"),
    rel("em_电能", "em_电功率", "requires"),
    rel("em_家庭电路", "em_串联", "applies_to"),
    rel("em_家庭电路", "em_并联", "applies_to"),
    rel("em_安全用电", "em_家庭电路", "applies_to"),
    rel("em_电场线", "em_电荷", "requires"),
    rel("em_磁场", "em_电荷", "requires"),
    rel("em_磁感线", "em_磁场", "representation"),
    rel("em_电磁铁", "em_磁场", "requires"),
    rel("em_电磁感应", "em_磁场", "requires"),
    rel("em_发电机", "em_电磁感应", "applies_to"),
    rel("em_电动机", "em_磁场", "applies_to"),
    rel("em_变压器", "em_电磁感应", "requires"),
    rel("em_交流电", "em_电磁感应", "applies_to"),
    rel("em_直流电", "em_电流", "specialization"),
    rel("em_超导现象", "em_电阻", "generalization"),

    rel("em_库仑定律", "em_电荷", "requires"),
    rel("em_电场强度", "em_库仑定律", "prerequisite"),
    rel("em_点电荷电场", "em_电场强度", "specialization"),
    rel("em_电场叠加", "em_电场强度", "applies_to"),
    rel("em_电势", "em_电场强度", "prerequisite"),
    rel("em_电势差", "em_电势", "representation"),
    rel("em_等势面", "em_电势", "representation"),
    rel("em_电势能", "em_电势", "requires"),
    rel("em_电容", "em_电势", "requires"),
    rel("em_平行板电容器", "em_电容", "specialization"),
    rel("em_电容器的充放电", "em_电容", "applies_to"),
    rel("em_电场力做功", "em_电势能", "requires"),
    rel("em_电阻定律", "em_电阻", "representation"),
    rel("em_电阻率", "em_电阻定律", "representation"),
    rel("em_基尔霍夫定律", "em_欧姆定律", "generalization"),
    rel("em_洛伦兹力", "em_磁场", "requires"),
    rel("em_洛伦兹力", "em_电流", "requires"),
    rel("em_安培力", "em_磁场", "requires"),
    rel("em_安培力", "em_电流", "requires"),
    rel("em_磁通量", "em_磁场", "requires"),
    rel("em_法拉第电磁感应定律", "em_磁通量", "requires"),
    rel("em_楞次定律", "em_法拉第电磁感应定律", "representation"),
    rel("em_自感", "em_法拉第电磁感应定律", "specialization"),
    rel("em_互感", "em_自感", "generalization"),
    rel("em_电感", "em_自感", "generalization"),
    rel("em_交变电流的产生", "em_电磁感应", "applies_to"),
    rel("em_交变电流的描述", "em_交变电流的产生", "representation"),
    rel("em_有效值", "em_交变电流的描述", "representation"),
    rel("em_变压器原理", "em_互感", "applies_to"),
    rel("em_远距离输电", "em_变压器原理", "applies_to"),
    rel("em_霍尔效应", "em_洛伦兹力", "applies_to"),
    rel("em_涡流", "em_电磁感应", "specialization"),

    rel("em_高斯定理", "em_电场强度", "generalization"),
    rel("em_安培环路定理", "em_磁场", "generalization"),
    rel("em_电位移", "em_高斯定理", "representation"),
    rel("em_电介质", "em_电容", "requires"),
    rel("em_电介质极化", "em_电介质", "representation"),
    rel("em_电场能量", "em_电容", "requires"),
    rel("em_磁场能量", "em_电感", "requires"),
    rel("em_位移电流", "em_安培环路定理", "generalization"),
    rel("em_麦克斯韦方程组", "em_高斯定理", "generalization"),
    rel("em_麦克斯韦方程组", "em_安培环路定理", "generalization"),
    rel("em_麦克斯韦方程组", "em_法拉第电磁感应定律", "generalization"),
    rel("em_麦克斯韦方程组", "em_位移电流", "generalization"),
    rel("em_电磁波", "em_麦克斯韦方程组", "representation"),
    rel("em_电磁波谱", "em_电磁波", "representation"),
    rel("em_坡印廷矢量", "em_电场能量", "requires"),
    rel("em_坡印廷矢量", "em_磁场能量", "requires"),
    rel("em_电磁场的边界条件", "em_麦克斯韦方程组", "applies_to"),
    rel("em_磁介质", "em_安培环路定理", "applies_to"),
    rel("em_磁化强度", "em_磁介质", "representation"),
    rel("em_铁磁性", "em_磁介质", "specialization"),
    rel("em_磁滞回线", "em_铁磁性", "representation"),
    rel("em_超导体", "em_电介质", "analogy"),
    rel("em_迈斯纳效应", "em_超导体", "representation"),
    rel("em_电磁感应定律的微分形式", "em_法拉第电磁感应定律", "generalization"),

    # ── Optics ──
    rel("optics_光的直线传播", "mechanics_运动", "analogy"),
    rel("optics_光的反射", "optics_光的直线传播", "prerequisite"),
    rel("optics_平面镜成像", "optics_光的反射", "applies_to"),
    rel("optics_光的折射", "optics_光的反射", "prerequisite"),
    rel("optics_折射定律", "optics_光的折射", "representation"),
    rel("optics_色散", "optics_光的折射", "applies_to"),
    rel("optics_凸透镜", "optics_光的折射", "applies_to"),
    rel("optics_凹透镜", "optics_光的折射", "applies_to"),
    rel("optics_透镜成像规律", "optics_凸透镜", "applies_to"),
    rel("optics_光的色散", "optics_色散", "representation"),
    rel("optics_光谱", "optics_光的色散", "representation"),
    rel("optics_红外线", "optics_光谱", "part_of"),
    rel("optics_紫外线", "optics_光谱", "part_of"),
    rel("optics_光的能量", "optics_光谱", "requires"),

    rel("optics_全反射", "optics_光的折射", "applies_to"),
    rel("optics_临界角", "optics_全反射", "representation"),
    rel("optics_光纤", "optics_全反射", "applies_to"),
    rel("optics_光导纤维", "optics_光纤", "representation"),
    rel("optics_光的干涉", "mechanics_波的干涉", "generalization"),
    rel("optics_双缝干涉", "optics_光的干涉", "specialization"),
    rel("optics_薄膜干涉", "optics_光的干涉", "specialization"),
    rel("optics_光的衍射", "mechanics_波的衍射", "generalization"),
    rel("optics_单缝衍射", "optics_光的衍射", "specialization"),
    rel("optics_光栅", "optics_光的衍射", "applies_to"),
    rel("optics_偏振", "optics_光的折射", "prerequisite"),
    rel("optics_自然光", "optics_偏振", "generalization"),
    rel("optics_偏振光", "optics_偏振", "generalization"),
    rel("optics_马吕斯定律", "optics_偏振光", "representation"),
    rel("optics_布儒斯特定律", "optics_光的反射", "applies_to"),
    rel("optics_光的偏振应用", "optics_偏振光", "applies_to"),

    rel("optics_光的相干性", "optics_光的干涉", "requires"),
    rel("optics_相干长度", "optics_光的相干性", "representation"),
    rel("optics_多光束干涉", "optics_光的干涉", "generalization"),
    rel("optics_法布里-珀罗干涉仪", "optics_多光束干涉", "applies_to"),
    rel("optics_光的偏振态", "optics_偏振", "generalization"),
    rel("optics_椭圆偏振", "optics_光的偏振态", "specialization"),
    rel("optics_圆偏振", "optics_椭圆偏振", "specialization"),
    rel("optics_波片", "optics_光的偏振态", "requires"),
    rel("optics_半波片", "optics_波片", "specialization"),
    rel("optics_四分之一波片", "optics_波片", "specialization"),
    rel("optics_双折射", "optics_光的折射", "generalization"),
    rel("optics_旋光性", "optics_偏振光", "specialization"),
    rel("optics_吸收光谱", "optics_光谱", "specialization"),
    rel("optics_发射光谱", "optics_光谱", "specialization"),
    rel("optics_连续光谱", "optics_光谱", "specialization"),
    rel("optics_线状光谱", "optics_光谱", "specialization"),
    rel("optics_带状光谱", "optics_光谱", "specialization"),

    # ── Modern Physics ──
    rel("modern_光电效应", "optics_光的能量", "prerequisite"),
    rel("modern_光子", "modern_光电效应", "requires"),
    rel("modern_光子能量", "modern_光子", "representation"),
    rel("modern_逸出功", "modern_光电效应", "representation"),
    rel("modern_截止频率", "modern_光电效应", "representation"),
    rel("modern_康普顿效应", "modern_光子", "requires"),
    rel("modern_波粒二象性", "modern_光电效应", "prerequisite"),
    rel("modern_波粒二象性", "modern_康普顿效应", "prerequisite"),
    rel("modern_德布罗意波", "modern_波粒二象性", "representation"),
    rel("modern_原子核式结构", "em_电荷", "prerequisite"),
    rel("modern_玻尔模型", "modern_原子核式结构", "prerequisite"),
    rel("modern_能级跃迁", "modern_玻尔模型", "representation"),
    rel("modern_光谱分析", "modern_能级跃迁", "applies_to"),
    rel("modern_氢原子光谱", "modern_能级跃迁", "applies_to"),
    rel("modern_放射性", "modern_原子核式结构", "prerequisite"),
    rel("modern_α衰变", "modern_放射性", "specialization"),
    rel("modern_β衰变", "modern_放射性", "specialization"),
    rel("modern_γ射线", "modern_放射性", "specialization"),
    rel("modern_半衰期", "modern_放射性", "representation"),
    rel("modern_原子核的组成", "modern_原子核式结构", "representation"),
    rel("modern_核力", "modern_原子核的组成", "requires"),
    rel("modern_质量数", "modern_原子核的组成", "representation"),
    rel("modern_电荷数", "modern_原子核的组成", "representation"),
    rel("modern_同位素", "modern_原子核的组成", "specialization"),
    rel("modern_核裂变", "modern_核力", "applies_to"),
    rel("modern_核聚变", "modern_核力", "applies_to"),
    rel("modern_链式反应", "modern_核裂变", "applies_to"),
    rel("modern_核反应堆", "modern_链式反应", "applies_to"),
    rel("modern_原子弹", "modern_核裂变", "applies_to"),
    rel("modern_氢弹", "modern_核聚变", "applies_to"),
    rel("modern_质能方程", "modern_核裂变", "requires"),
    rel("modern_质能方程", "modern_核聚变", "requires"),

    rel("modern_狭义相对论", "mechanics_牛顿第二定律", "generalization"),
    rel("modern_洛伦兹变换", "modern_狭义相对论", "representation"),
    rel("modern_时间膨胀", "modern_洛伦兹变换", "representation"),
    rel("modern_长度收缩", "modern_洛伦兹变换", "representation"),
    rel("modern_同时性的相对性", "modern_洛伦兹变换", "representation"),
    rel("modern_质速关系", "modern_狭义相对论", "representation"),
    rel("modern_四维动量", "modern_狭义相对论", "representation"),
    rel("modern_不确定性原理", "modern_德布罗意波", "prerequisite"),
    rel("modern_波函数", "modern_不确定性原理", "prerequisite"),
    rel("modern_薛定谔方程", "modern_波函数", "prerequisite"),
    rel("modern_量子态", "modern_薛定谔方程", "representation"),
    rel("modern_量子叠加", "modern_量子态", "representation"),
    rel("modern_量子隧穿", "modern_薛定谔方程", "applies_to"),
    rel("modern_泡利不相容原理", "modern_量子态", "prerequisite"),
    rel("modern_费米子", "modern_泡利不相容原理", "representation"),
    rel("modern_玻色子", "modern_费米子", "analogy"),
    rel("modern_光子统计", "modern_光子", "requires"),
    rel("modern_激光", "modern_光子", "applies_to"),
    rel("modern_受激辐射", "modern_激光", "representation"),
    rel("modern_自发辐射", "modern_激光", "representation"),
    rel("modern_粒子物理标准模型", "modern_夸克", "generalization"),
    rel("modern_希格斯机制", "modern_粒子物理标准模型", "representation"),
    rel("modern_广义相对论简介", "modern_狭义相对论", "generalization"),
    rel("modern_引力波", "modern_广义相对论简介", "representation"),

    # ── Fluid Mechanics ──
    rel("fluid_流体静力学", "mechanics_压强", "generalization"),
    rel("fluid_帕斯卡定律", "fluid_流体静力学", "representation"),
    rel("fluid_伯努利方程", "mechanics_流体压强", "generalization"),
    rel("fluid_粘性", "mechanics_摩擦力", "analogy"),
    rel("fluid_层流", "fluid_粘性", "specialization"),
    rel("fluid_湍流", "fluid_层流", "analogy"),
    rel("fluid_雷诺数", "fluid_层流", "requires"),
    rel("fluid_雷诺数", "fluid_湍流", "requires"),
    rel("fluid_泊肃叶定律", "fluid_层流", "applies_to"),
    rel("fluid_斯托克斯定律", "fluid_粘性", "applies_to"),
    rel("fluid_表面张力", "thermo_分子动理论", "requires"),
    rel("fluid_毛细现象", "fluid_表面张力", "applies_to"),
    rel("fluid_连续性方程", "fluid_伯努利方程", "prerequisite"),

    # ── Nuclear & Particle ──
    rel("nuclear_放射性衰变规律", "modern_放射性", "representation"),
    rel("nuclear_衰变常数", "nuclear_放射性衰变规律", "representation"),
    rel("nuclear_比活度", "nuclear_放射性衰变规律", "representation"),
    rel("nuclear_核反应截面", "modern_核力", "requires"),
    rel("nuclear_中子", "modern_原子核的组成", "part_of"),
    rel("nuclear_质子", "modern_原子核的组成", "part_of"),
    rel("nuclear_电子", "modern_原子核式结构", "part_of"),
    rel("nuclear_正电子", "nuclear_电子", "analogy"),
    rel("nuclear_中微子", "modern_β衰变", "requires"),
    rel("nuclear_夸克", "modern_粒子物理标准模型", "part_of"),
    rel("nuclear_轻子", "modern_粒子物理标准模型", "part_of"),
    rel("nuclear_介子", "nuclear_夸克", "generalization"),
    rel("nuclear_强相互作用", "modern_核力", "representation"),
    rel("nuclear_弱相互作用", "modern_β衰变", "representation"),
    rel("nuclear_电磁相互作用", "em_库仑定律", "generalization"),
    rel("nuclear_引力相互作用", "mechanics_万有引力", "generalization"),
]

# ══════════════════════════════════════════════════════════════════════
#  BUILD OUTPUT
# ══════════════════════════════════════════════════════════════════════

all_concepts = []
for g in all_groups:
    c = build_concept(g)
    if c is not None:
        all_concepts.append(c)

# Deduplicate by name
seen = set()
unique_concepts = []
for c in all_concepts:
    if c["name"] not in seen:
        seen.add(c["name"])
        unique_concepts.append(c)

# Deduplicate relations
seen_rels = set()
unique_relations = []
for r in relations:
    key = (r["source"], r["target"], r["type"])
    if key not in seen_rels:
        seen_rels.add(key)
        unique_relations.append(r)

output = {
    "version": "2.0",
    "domain": "physics",
    "description": "Expanded Physics knowledge graph — elementary through university, trilingual (ZH/EN/DE). 200+ concepts, 10+ publishers per language.",
    "languages": ["zh", "en", "de"],
    "created": datetime.now().isoformat(),
    "pipeline": "scripts/expand_physics_graph.py",
    "publisher_counts": {
        "zh": sum(len(v) for v in ZH_PUBLISHERS.values()),
        "en": sum(len(v) for v in EN_PUBLISHERS.values()),
        "de": sum(len(v) for v in DE_PUBLISHERS.values()),
    },
    "concepts": unique_concepts,
    "relations": unique_relations,
    "metadata": {
        "total_concepts": len(unique_concepts),
        "total_relations": len(unique_relations),
        "created": datetime.now().isoformat()
    }
}

# Level distribution
from collections import Counter
level_dist = Counter(c["level"] for c in unique_concepts)

print(f"Total concepts: {len(unique_concepts)}")
print(f"Total relations: {len(unique_relations)}")
print(f"Level distribution: {dict(level_dist)}")
print(f"Publishers: ZH={output['publisher_counts']['zh']}, EN={output['publisher_counts']['en']}, DE={output['publisher_counts']['de']}")

with open(OUTPUT, "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"\n[OK] Written to {OUTPUT}")
