#!/usr/bin/env python3
"""
LinguaGraph — Unified Release Pipeline

One command to:
  1. Run math graph pipeline (merge → align → export → validate)
  2. Run quality report with gate checks
  3. If gates pass: export data.js + copy to deploy
  4. If gates fail: STOP with error report
  5. Generate release_report.md

Usage:
    python scripts/release.py
    python scripts/release.py --dry-run     # Preview without writing
    python scripts/release.py --skip-pipeline  # Use existing data, re-check only
    python scripts/release.py --verbose
"""

import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
RELEASE_DIR = PROJECT_ROOT / "release"


def banner(title: str) -> None:
    print(f"\n{'=' * 55}")
    print(f"  {title}")
    print(f"{'=' * 55}\n")


def run(cmd: list[str], desc: str, cwd: str | None = None) -> subprocess.CompletedProcess:
    """Run a command and return the result."""
    print(f"  [{desc}]")
    print(f"    {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd or str(PROJECT_ROOT),
                            capture_output=True, text=True)
    if result.returncode != 0:
        print(f"    [FAIL] exit code {result.returncode}")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-5:]:
                print(f"    > {line}")
    else:
        # Print last line of stdout as summary
        lines = [l for l in result.stdout.strip().split("\n") if l.strip()]
        if lines:
            print(f"    [OK] {lines[-1][:100]}")
    return result


def run_pipeline() -> bool:
    """Step 1: Math graph pipeline."""
    banner("STEP 1: Pipeline (merge → align → export → validate)")
    result = run(
        [sys.executable, "scripts/math_graph_pipeline/run_pipeline.py"],
        "run_pipeline.py",
    )
    return result.returncode == 0


def run_quality_report() -> tuple[bool, dict | None]:
    """Step 2: Quality report with gates."""
    banner("STEP 2: Quality Report + Gates")
    result = run(
        [sys.executable, "scripts/quality_report.py", "--check-quality-gates"],
        "quality_report.py --check-quality-gates",
    )
    if result.returncode != 0:
        return False, None

    # Parse the latest quality report for gate/drift info
    latest = Path(PROJECT_ROOT) / "data" / "quality_history" / "quality_report_latest.json"
    if latest.exists():
        try:
            report = json.loads(latest.read_text(encoding="utf-8"))
            return True, report
        except (json.JSONDecodeError, Exception):
            return True, None
    return True, None


def check_gates(report: dict | None) -> bool:
    """Step 3: Check if gates passed and drift is acceptable."""
    banner("STEP 3: Gate Check")

    # Quality gates result
    gates = (report or {}).get("quality_gates", {})
    gates_ok = gates.get("exit_code") == 0 if gates else True

    if not gates_ok:
        print("  [FAIL] Quality gates: FAILED")
        print("  See output above for details.")
        return False

    # Drift warnings
    diff = (report or {}).get("diff")
    if diff:
        warnings = [d for d in diff if d.get("severity") == "WARN"]
        if warnings:
            print(f"  [WARN] {len(warnings)} drift warning(s) found:")
            for d in warnings:
                print(f"    {d['metric']}: {d['old']} -> {d['new']} ({d.get('delta_pct', '?')}%)")
            print("  Release continues but review recommended.")
        else:
            print("  [OK] No significant drift")
    else:
        print("  [OK] No drift detected (first run or stable)")

    print("  [PASS] All checks OK")
    return True


def export_and_deploy() -> bool:
    """Step 4: Export data.js and copy to deploy directory."""
    banner("STEP 4: Export + Deploy")

    # Read visualization data
    vis_path = PROJECT_ROOT / "data" / "math_extractions" / "merged" / "visualization_data.json"
    if not vis_path.exists():
        print("  [FAIL] visualization_data.json not found — run pipeline first")
        return False

    try:
        vis = json.loads(vis_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, Exception) as e:
        print(f"  [FAIL] Cannot read visualization data: {e}")
        return False

    # Generate data.js
    js = "// CognitiveSpace — 3D Knowledge Graph Data\n"
    js += "// Auto-generated by release.py\n"
    js += f"// Version: 2.0 | {vis['metadata']['total_nodes']} nodes | {len(vis['links'])} links\n"
    js += f"// Generated: {vis['generated_at']}\n\n"
    js += "var data = " + json.dumps(vis, ensure_ascii=False, indent=2) + ";\n"

    data_js_path = PROJECT_ROOT / "cognitive-space" / "web" / "data.js"
    data_js_path.write_text(js, encoding="utf-8")
    js_size = len(js)
    print(f"  [OK] data.js: {js_size:,} bytes -> {data_js_path.relative_to(PROJECT_ROOT)}")

    # Copy to deploy
    deploy_path = PROJECT_ROOT / "_deploy" / "data.js"
    deploy_path.write_text(js, encoding="utf-8")
    print(f"  [OK] _deploy/data.js: {js_size:,} bytes")

    return True


def generate_release_report(report: dict | None, gates_ok: bool) -> Path:
    """Step 5: Generate release_report.md."""
    banner("STEP 5: Release Report")

    gm = (report or {}).get("graph_metrics", {})
    am = (report or {}).get("alignment_metrics", {})
    checksums = (report or {}).get("file_checksums", {})
    diff = (report or {}).get("diff")

    warnings = [d for d in (diff or []) if d.get("severity") == "WARN"]
    infos = [d for d in (diff or []) if d.get("severity") == "INFO"]

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md = f"""# LinguaGraph — Release Report

**Generated:** {timestamp}
**Pipeline version:** {(report or {}).get('pipeline_version', 'unknown')}
**Gates:** {'PASS' if gates_ok else 'FAIL'}
**Drift:** {len(warnings)} warning(s), {len(infos)} minor change(s)

---

## Graph Metrics

| Metric | Value |
|--------|-------|
| Nodes | {gm.get('nodes', '?')} (unique: {gm.get('unique_ids', '?')}) |
| Links | {gm.get('links', '?')} |
| Graph Density | {gm.get('graph_density', '?')} |
| Avg Degree | {gm.get('avg_degree', '?')} |
| Median Degree | {gm.get('degree_median', '?')} |
| P95 Degree | {gm.get('degree_p95', '?')} |
| Max Degree | {gm.get('degree_max', '?')} |
| Degree=0 | {gm.get('degree_zeros', '?')} |
| Components | {gm.get('connected_components', '?')} (largest: {gm.get('largest_component_size', '?')}) |

## Alignment Metrics

| Metric | Value |
|--------|-------|
| Aligned Groups | {am.get('aligned_groups', '?')} |
| Trilingual | {am.get('trilingual_groups', '?')} / {am.get('aligned_groups', '?')} |
| Unmatched | {am.get('unmatched_concepts', '?')} |
| Relations | {am.get('total_relations', '?')} |
| Levels | {json.dumps(am.get('level_name_distribution', {}))} |

## File Checksums

| File | MD5 |
|------|-----|
| data.js | {checksums.get('data.js', 'N/A')} |
| visualization_data.json | {checksums.get('visualization_data.json', 'N/A')} |
| aligned_data.json | {checksums.get('aligned_data.json', 'N/A')} |

"""

    if diff:
        md += "## Changes from Previous Release\n\n"
        md += "| Metric | Old | New | Delta | Severity |\n"
        md += "|--------|-----|-----|-------|----------|\n"
        for d in diff:
            icon = ":warning:" if d["severity"] == "WARN" else ":information_source:"
            pct = f" ({d['delta_pct']}%)" if d.get('delta_pct') is not None else ""
            md += f"| {d['metric']} | {d['old']} | {d['new']} | {d['delta']:+d}{pct} | {icon} |\n"

    md += "\n---\n"
    md += f"_Auto-generated by `scripts/release.py` at {timestamp}_\n"

    report_path = PROJECT_ROOT / "data" / "quality_history" / "release_report.md"
    report_path.write_text(md, encoding="utf-8")
    print(f"  [OK] release_report.md -> {report_path.relative_to(PROJECT_ROOT)}")
    return report_path


def generate_manifest_bundle() -> bool:
    """Step 6: Generate manifest.json (single source of truth)."""
    banner("STEP 6: Manifest")
    result = run(
        [sys.executable, "scripts/generate_manifest.py"],
        "generate_manifest.py",
    )
    return result.returncode == 0


def create_release_bundle(report: dict | None, gates_ok: bool) -> Path:
    """Step 7: Assemble release bundle in release/ directory."""
    banner("STEP 7: Release Bundle")

    # Clean and recreate
    if RELEASE_DIR.exists():
        shutil.rmtree(RELEASE_DIR)
    RELEASE_DIR.mkdir(parents=True)

    # Files to bundle
    bundle_files = [
        ("manifest.json", PROJECT_ROOT / "manifest.json"),
        ("data.js", PROJECT_ROOT / "cognitive-space" / "web" / "data.js"),
        ("data/visualization_data.json", PROJECT_ROOT / "data" / "math_extractions" / "merged" / "visualization_data.json"),
        ("data/aligned_data.json", PROJECT_ROOT / "data" / "math_extractions" / "merged" / "aligned_data.json"),
        ("report/release_report.md", PROJECT_ROOT / "data" / "quality_history" / "release_report.md"),
        ("report/quality_report.json", PROJECT_ROOT / "data" / "quality_history" / "quality_report_latest.json"),
        ("checksums.txt", None),
    ]

    checksums: list[str] = []
    for rel_path, src_path in bundle_files:
        if src_path is None:
            continue  # placeholder, handled below
        if src_path.exists():
            dest = RELEASE_DIR / rel_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dest)
            size = src_path.stat().st_size
            md5_val = hashlib.md5(src_path.read_bytes()).hexdigest()[:16]
            checksums.append(f"{md5_val}  {size:>10,}  {rel_path}")
            print(f"  [OK] {rel_path} ({size:,} bytes)")

    # Generate checksums.txt
    (RELEASE_DIR / "checksums.txt").write_text(
        "# LinguaGraph Release Bundle Checksums\n"
        f"# Generated: {datetime.now().isoformat(timespec='seconds')}\n"
        f"# Format: <md5>  <size>  <path>\n\n"
        + "\n".join(checksums) + "\n",
        encoding="utf-8",
    )
    print(f"  [OK] checksums.txt ({len(checksums)} entries)")

    bundle_size = sum(f.stat().st_size for f in RELEASE_DIR.rglob("*") if f.is_file())
    print(f"\n  Bundle: {RELEASE_DIR.relative_to(PROJECT_ROOT)}/ ({bundle_size:,} bytes total)")
    return RELEASE_DIR


def main():
    import argparse
    parser = argparse.ArgumentParser(description="LinguaGraph unified release pipeline")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview steps without writing")
    parser.add_argument("--skip-pipeline", action="store_true",
                        help="Skip pipeline, use existing data")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print("\n")
    print("  ██╗     ██╗███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ "
          " ██████╗ ██████╗  █████╗ ██████╗ ██╗  ██╗")
    print("  ██║     ██║████╗  ██║██╔════╝ ██║   ██║██╔══██╗"
          "██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██║  ██║")
    print("  ██║     ██║██╔██╗ ██║██║  ███╗██║   ██║███████║"
          "██║  ███╗██████╔╝███████║██████╔╝███████║")
    print("  ██║     ██║██║╚██╗██║██║   ██║██║   ██║██╔══██║"
          "██║   ██║██╔══██╗██╔══██║██╔══██╗██╔══██║")
    print("  ███████╗██║██║ ╚████║╚██████╔╝╚██████╔╝██║  ██║"
          "╚██████╔╝██║  ██║██║  ██║██║  ██║██║  ██║")
    print("  ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝"
          " ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝")
    print(f"\n  {'Dry Run' if args.dry_run else 'Release Pipeline'}")
    if args.skip_pipeline:
        print("  [SKIP] Pipeline step (--skip-pipeline)")
    print()

    pipeline_ok = True
    if not args.skip_pipeline:
        pipeline_ok = run_pipeline()
        if not pipeline_ok:
            print("\n  [FATAL] Pipeline failed — stopping release")
            sys.exit(1)

    gates_ok, report = run_quality_report()
    if not gates_ok:
        print("\n  [FATAL] Quality report failed — stopping release")
        sys.exit(1)

    gates_ok = check_gates(report)
    if not gates_ok:
        print("\n  [FATAL] Gates failed — release blocked")
        print("  Fix issues above and re-run.")
        # Still generate a partial report for debugging
        generate_release_report(report, False)
        sys.exit(1)

    if not args.dry_run:
        deploy_ok = export_and_deploy()
        if not deploy_ok:
            print("\n  [FATAL] Export/deploy failed")
            sys.exit(1)
    else:
        print("\n  [DRY RUN] Skipping export + deploy\n")

    report_path = generate_release_report(report, True)

    manifest_ok = generate_manifest_bundle()
    if not manifest_ok:
        print("\n  [FATAL] Manifest generation failed")
        sys.exit(1)

    if not args.dry_run:
        create_release_bundle(report, True)
    else:
        print("\n  [DRY RUN] Skipping release bundle")

    if args.dry_run:
        print(f"\n{'=' * 55}")
        print("  DRY RUN COMPLETE — no files written")
        print(f"{'=' * 55}")
    else:
        print(f"\n{'=' * 55}")
        print("  RELEASE COMPLETE")
        print(f"{'=' * 55}")
        print(f"  Report: {report_path.relative_to(PROJECT_ROOT)}")
        print(f"  Viewer: cognitive-space/web/data.js")
        print(f"  Deploy: _deploy/data.js")
        print(f"  Bundle: release/")
        print(f"{'=' * 55}")


if __name__ == "__main__":
    main()
